import type { NamesByGender } from "src/constants/markovNamePresets"

const ELVISH_MALE_NAMES = [
    "Aegnor", "Aelindor", "Aerandir", "Aerdan", "Aerendir", "Aerion", "Aldaron",
    "Almarion", "Amandil", "Amdir", "Amras", "Amrod", "Amroth", "Anairo",
    "Anardil", "Anarion", "Anborn", "Angrod", "Annael", "Aradan", "Arandur",
    "Aranion", "Aranwe", "Arathil", "Arcamenel", "Aredhir", "Arminas",
    "Arthion", "Beleg", "Belegorn", "Belegund", "Beren", "Borlad", "Brandir",
    "Caladhir", "Calaron", "Calenhir", "Calimmacil", "Caranion", "Caranthir",
    "Celeborn", "Celebrimbor", "Celebrindor", "Celegorm", "Celendir",
    "Cemendur", "Cirdan", "Cirion", "Curufin", "Curunir", "Daerandil",
    "Daerion", "Daeron", "Denethor", "Dior", "Dirhael", "Duilin", "Duinhir",
    "Duinor", "Earendil", "Ecthelion", "Edhelion", "Edrahil", "Egalion",
    "Egalmoth", "Eldamir", "Eldarion", "Elemmakil", "Elendil", "Elenhir",
    "Elenion", "Elerion", "Elladan", "Elladir", "Elmo", "Elrohir", "Elrond",
    "Elros", "Eluchil", "Elured", "Elurin", "Enel", "Enerdhil", "Eol",
    "Erellont", "Erestor", "Erynion", "Faelivrin", "Faelon", "Faenor",
    "Falassion", "Falathar", "Faroth", "Feanor", "Finarfin", "Finellach",
    "Fingolfin", "Fingon", "Finrod", "Finwe", "Galadhon", "Galathon", "Galdor",
    "Galion", "Gelmir", "Gil-galad", "Gildinor", "Gildor", "Gilmith",
    "Gilrandir", "Glorfindel", "Glorion", "Guilin", "Gwaerion", "Gwaeron",
    "Gwathir", "Gwindor", "Haldamir", "Haldir", "Hallatan", "Heledhon",
    "Hirgon", "Hirluin", "Idrilion", "Imrahil", "Ingil", "Inglor", "Ingwe",
    "Ingwion", "Irmo", "Ithilbor", "Ithildor", "Lathron", "Legolas", "Lenwe",
    "Lindir", "Lindorion", "Lothion", "Luinor", "Mablung", "Maedhros",
    "Maeglin", "Maglor", "Mahtan", "Malbeth", "Malgalad", "Mallor", "Meneldil",
    "Minalcar", "Mirdan", "Mirdanor", "Mornion", "Nauron", "Nelion",
    "Nerdanion", "Nimrion", "Norion", "Nurion", "Ohtar", "Olwe", "Orithil",
    "Orodhil", "Orodreth", "Oropher", "Orophin", "Orophir", "Palanor",
    "Pengolodh", "Randir", "Rhavan", "Rhovandil", "Rhuindor", "Rodnor", "Rumil",
    "Rumildur", "Saeldur", "Saeros", "Silmarion", "Silmien", "Sirion", "Tarcil",
    "Tathar", "Tauron", "Telchar", "Telemnar", "Thalanor", "Thingol",
    "Thranduil", "Tindomion", "Tinnudir", "Tinwion", "Tuor", "Turambar",
    "Turgon", "Valandil", "Vanyandil", "Vardamir", "Vorondil", "Voronwe",
    "Voronwion",
]
const ELVISH_FEMALE_NAMES = [
    "Aeglosiel", "Aelinel", "Aelwen", "Aeriel", "Aerin", "Aerwen", "Alassiel",
    "Alfirin", "Almiel", "Alquawen", "Amaranthe", "Amarie", "Amariel",
    "Amarthiel", "Anaire", "Anariel", "Anarwen", "Ancalime", "Andreth",
    "Anoriel", "Anorwen", "Aranel", "Aranwen", "Aredhel", "Arien", "Arphenel",
    "Arwen", "Arwenel", "Belemiel", "Beleth", "Belethiel", "Beliriel",
    "Brethiliel", "Brithiel", "Caladwen", "Calaniel", "Caleniel", "Calmiel",
    "Celairiel", "Celebrian", "Celebriel", "Celebrindal", "Celebwen",
    "Celeniel", "Cirieth", "Daeriel", "Earnien", "Earwen", "Elaniel", "Elanor",
    "Elbereth", "Eledhwen", "Elemmire", "Elenna", "Elenril", "Elentari",
    "Elenwe", "Elerrina", "Elestriel", "Eliniel", "Elloth", "Elwen", "Elwing",
    "Emeldir", "Erendis", "Eriel", "Eruwen", "Estelinde", "Estelwen",
    "Faelinel", "Faniel", "Findis", "Finduilas", "Finwen", "Galadriel",
    "Galadwen", "Galathiel", "Galwen", "Gelwen", "Gilraen", "Gilraeniel",
    "Gilwen", "Glirwen", "Glorwen", "Gwirith", "Haleth", "Heledir", "Heledwen",
    "Hiriel", "Idhrenwen", "Idhrien", "Idril", "Ilmare", "Ilmariel", "Ilwen",
    "Indilwen", "Indis", "Irime", "Isilme", "Ithiliel", "Ithilwen", "Ithrien",
    "Laerwen", "Laire", "Lalaith", "Lalwen", "Laurelin", "Lindariel", "Lindiel",
    "Lindorie", "Lirimiel", "Lissuin", "Lomelinde", "Loriel", "Losswen",
    "Lothiriel", "Lothwen", "Luinil", "Luinwen", "Luthien", "Maethiel",
    "Maewen", "Mairen", "Malloriel", "Melian", "Melwen", "Meneliel", "Menelwen",
    "Mereth", "Minuial", "Mireth", "Miriel", "Mirimel", "Miriwen", "Mithiel",
    "Mithrellas", "Morniel", "Morwen", "Nariel", "Nellas", "Nenwen", "Nerdanel",
    "Nessa", "Nienna", "Nienor", "Nimeth", "Nimloth", "Nimphelos", "Nimriel",
    "Nimrien", "Nimrodel", "Nimwen", "Ninglorien", "Niniel", "Niphredil",
    "Niriel", "Nolwen", "Oloriel", "Orneth", "Orodwen", "Rhiwen", "Rhosiel",
    "Rian", "Rilien", "Rimwen", "Ruvalwen", "Silivren", "Silmarien", "Silwen",
    "Sirith", "Tarien", "Tathariel", "Tathwen", "Tauriel", "Taurwen",
    "Telperien", "Thaliel", "Tindomiel", "Tiniel", "Tinuviel", "Tinwen",
    "Tuiliel", "Uialwen", "Uinen", "Uinwen", "Undomiel", "Vaire", "Vairiel",
    "Vana", "Vanimelde", "Vanwen", "Vanyariel", "Varda", "Varniel", "Wilwarin",
    "Yavanna", "Yavetil", "Yaviel", "Yavien", "Yulmiel",
]
export const ELVISH_NAMES: NamesByGender = {
    male: ELVISH_MALE_NAMES,
    female: ELVISH_FEMALE_NAMES,
    neutral: [...ELVISH_MALE_NAMES, ...ELVISH_FEMALE_NAMES],
}
