import type { NamesByGender } from "src/constants/markovNamePresets"

export const ENGLISH_NAMES: NamesByGender = {
    male: [
        "Aaron", "Adam", "Adrian", "Alan", "Albert", "Alec", "Alexander",
        "Alfred", "Algernon", "Alistair", "Ambrose", "Andrew", "Anselm",
        "Anthony", "Archibald", "Arnold", "Arthur", "Augustus", "Austin",
        "Barnaby", "Barry", "Bartholomew", "Basil", "Benedict", "Benjamin",
        "Bernard", "Bertie", "Bertram", "Bradley", "Brian", "Bruce", "Cecil",
        "Cedric", "Charles", "Chester", "Christian", "Christopher", "Clarence",
        "Claude", "Clement", "Clifford", "Clive", "Colin", "Conrad", "Crispin",
        "Cuthbert", "Cyril", "Daniel", "David", "Dennis", "Derek", "Desmond",
        "Dominic", "Donald", "Douglas", "Dudley", "Duncan", "Edgar", "Edmund",
        "Edward", "Edwin", "Elliott", "Emmett", "Eric", "Ernest", "Eugene",
        "Evan", "Ewan", "Felix", "Ferdinand", "Fergus", "Francis", "Frank",
        "Frederick", "Gabriel", "Gareth", "Gavin", "Geoffrey", "George",
        "Gerald", "Gilbert", "Giles", "Godfrey", "Gordon", "Graham", "Gregory",
        "Guy", "Harold", "Harry", "Harvey", "Hector", "Henry", "Herbert",
        "Horace", "Howard", "Hubert", "Hugh", "Humphrey", "Ian", "Isaac",
        "Ivor", "Jack", "James", "Jasper", "Jeffrey", "Jeremiah", "Jeremy",
        "Jerome", "John", "Jonah", "Jonathan", "Joseph", "Julian", "Keith",
        "Kenneth", "Kevin", "Lancelot", "Laurence", "Lawrence", "Leonard",
        "Leopold", "Lewis", "Linus", "Lionel", "Lloyd", "Luke", "Magnus",
        "Malcolm", "Marcus", "Mark", "Martin", "Matthew", "Matthias", "Maurice",
        "Maxwell", "Michael", "Miles", "Montague", "Nathan", "Nathaniel",
        "Neil", "Nelson", "Neville", "Nicholas", "Nigel", "Norman", "Oliver",
        "Oscar", "Oswald", "Owen", "Patrick", "Paul", "Percival", "Percy",
        "Peter", "Philip", "Quentin", "Ralph", "Randolph", "Raymond",
        "Reginald", "Reuben", "Rex", "Richard", "Robert", "Rodney", "Roger",
        "Roland", "Ronald", "Rowland", "Rufus", "Rupert", "Russell", "Samuel",
        "Sebastian", "Silas", "Simon", "Solomon", "Stanley", "Stephen",
        "Stewart", "Stuart", "Terence", "Thaddeus", "Theodore", "Thomas",
        "Timothy", "Tobias", "Trevor", "Tristan", "Ulysses", "Vernon", "Victor",
        "Vincent", "Wallace", "Walter", "Warren", "Wilfred", "William",
        "Winston",
    ],
    female: [
        "Abigail", "Ada", "Adela", "Adelaide", "Agatha", "Agnes", "Alexandra",
        "Alice", "Alison", "Alma", "Amelia", "Amy", "Angela", "Annabel", "Anne",
        "Annie", "Arabella", "Audrey", "Barbara", "Beatrice", "Bella",
        "Bernadette", "Beryl", "Beth", "Blanche", "Bridget", "Camilla", "Carol",
        "Caroline", "Cassandra", "Catherine", "Cecily", "Celia", "Charity",
        "Charlotte", "Christina", "Claire", "Clara", "Clementine", "Constance",
        "Cordelia", "Cynthia", "Daisy", "Deborah", "Delia", "Diana", "Dinah",
        "Dora", "Doris", "Dorothy", "Edith", "Edna", "Eileen", "Elaine",
        "Eleanor", "Eliza", "Elizabeth", "Ella", "Eloise", "Elsie", "Emily",
        "Emma", "Enid", "Esther", "Ethel", "Eva", "Evelyn", "Faith", "Felicity",
        "Fiona", "Flora", "Florence", "Frances", "Freda", "Frederica", "Gemma",
        "Georgina", "Geraldine", "Gertrude", "Gillian", "Gladys", "Gloria",
        "Grace", "Gwen", "Gwendolyn", "Hannah", "Harriet", "Hazel", "Heather",
        "Helen", "Helena", "Henrietta", "Hester", "Hilda", "Honor", "Hope",
        "Imogen", "Irene", "Iris", "Isabel", "Isabella", "Ivy", "Jacqueline",
        "Jane", "Janet", "Jemima", "Jennifer", "Jessica", "Joan", "Jocelyn",
        "Josephine", "Joyce", "Judith", "Julia", "Julianne", "Juliet", "June",
        "Kate", "Katherine", "Kathleen", "Laura", "Lavinia", "Leonora",
        "Letitia", "Lillian", "Lorna", "Lottie", "Louisa", "Lucinda", "Lucy",
        "Lydia", "Mabel", "Madeline", "Maggie", "Margaret", "Marian",
        "Marjorie", "Martha", "Mary", "Matilda", "Maud", "Mavis", "Maxine",
        "May", "Meredith", "Mildred", "Millicent", "Minnie", "Miranda", "Molly",
        "Muriel", "Nancy", "Nell", "Nora", "Olive", "Olivia", "Pamela",
        "Patience", "Pauline", "Pearl", "Penelope", "Petra", "Philippa",
        "Phoebe", "Poppy", "Priscilla", "Prudence", "Rachel", "Rebecca",
        "Rosalind", "Rosamund", "Rose", "Rosemary", "Ruth", "Sabrina", "Sarah",
        "Selina", "Sheila", "Sibyl", "Sophia", "Stella", "Susan", "Susanna",
        "Sylvia", "Tabitha", "Teresa", "Tessa", "Theodora", "Una", "Ursula",
        "Vera", "Veronica", "Victoria", "Violet", "Vivian", "Wendy",
        "Wilhelmina", "Winifred", "Yvonne", "Zoe",
    ],
    neutral: [
        "Addison", "Ainsley", "Alden", "Alex", "Alexis", "Ali", "Amari",
        "Arden", "Ari", "Ariel", "Arley", "Ash", "Ashton", "Aspen", "Aubrey",
        "August", "Avery", "Bailey", "Bellamy", "Billie", "Blaine", "Blair",
        "Blake", "Blue", "Bobbie", "Brett", "Briar", "Brook", "Cameron",
        "Carlin", "Carson", "Cary", "Casey", "Cassidy", "Channing", "Charlie",
        "Chris", "Cody", "Corey", "Courtney", "Dakota", "Dale", "Dallas",
        "Dana", "Darby", "Darcy", "Dell", "Denver", "Devon", "Dorian", "Drew",
        "Dylan", "Eden", "Ellery", "Elliot", "Ellis", "Ellison", "Emerson",
        "Emery", "Emory", "Finlay", "Finley", "Frankie", "Gale", "Glenn",
        "Gray", "Greer", "Hadley", "Harley", "Harlow", "Harper", "Haven",
        "Hayden", "Hayes", "Holland", "Hollis", "Hunter", "Indigo", "Jackie",
        "Jaden", "Jaime", "Jamie", "Jay", "Jesse", "Jessie", "Jody", "Joey",
        "Jordan", "Jude", "Jules", "Justice", "Kacey", "Kai", "Kelly",
        "Kendall", "Kennedy", "Kerry", "Kim", "Kit", "Kris", "Lake", "Lane",
        "Lark", "Laurie", "Lee", "Leigh", "Lennon", "Lennox", "Leslie",
        "Linden", "Lindsay", "Logan", "London", "Lou", "Lynn", "Mackenzie",
        "Madison", "Marion", "Marley", "Marlowe", "Max", "Mel", "Merle",
        "Merritt", "Micah", "Milan", "Monroe", "Morgan", "Nicky", "Nico", "Noa",
        "Noel", "Oakley", "Ocean", "Ollie", "Parker", "Pat", "Payton", "Perry",
        "Peyton", "Phoenix", "Presley", "Quincy", "Quinn", "Raleigh", "Ray",
        "Reagan", "Reed", "Reese", "Remington", "Remy", "Rene", "Ridley",
        "Riley", "River", "Robbie", "Robin", "Ronnie", "Rory", "Rowan", "Sage",
        "Sam", "Sandy", "Sasha", "Sawyer", "Scout", "Shannon", "Shawn", "Shay",
        "Shelby", "Shiloh", "Sidney", "Sky", "Skyler", "Spencer", "Stacy",
        "Sterling", "Stevie", "Storm", "Sunny", "Sutton", "Sydney", "Tate",
        "Tatum", "Taylor", "Teagan", "Terry", "Tobin", "Toby", "Toni", "Tracy",
        "Tyler", "Val", "Wallis", "Whitney", "Winter", "Wren", "Wynn", "Yael",
        "Zion",
    ],
}
