export const ENGLISH_WORDS = [
    "abacus", "abbey", "accordion", "acorn", "acre", "acrobat", "adder",
    "admiral", "adventure", "aerie", "alchemy", "alder", "alley", "almanac",
    "almond", "aloe", "alpine", "altar", "amber", "amethyst", "amulet",
    "anchor", "angel", "anise", "anthem", "antler", "anvil", "apex",
    "apiary", "apple", "apricot", "apron", "aqua", "arbor", "arcade",
    "arch", "archer", "arena", "aria", "ark", "armor", "aroma", "arrow",
    "arrowhead", "artisan", "ash", "aspen", "aster", "atlas", "attic",
    "aurora", "autumn", "avalanche", "avenue", "aviary", "awning", "axle",
    "azure", "badge", "badger", "bagpipe", "baker", "balcony", "ballad",
    "balloon", "bamboo", "bandit", "banjo", "banner", "barley", "barn",
    "barrel", "basil", "basin", "basket", "bay", "bayou", "beach", "beacon",
    "bead", "beam", "bear", "beaver", "bee", "beetle", "bell", "bellow",
    "bench", "berry", "birch", "biscuit", "bishop", "blade", "blanket",
    "blaze", "bloom", "blossom", "bluebell", "boat", "bonfire", "boulder",
    "bounty", "bower", "bracken", "bramble", "branch", "brass", "bread",
    "breeze", "brick", "bridge", "bronze", "brook", "broom", "bubble",
    "buckle", "bugle", "butter", "cabbage", "cabin", "cactus", "cadence",
    "calico", "calm", "camel", "cameo", "camp", "canal", "canary", "candle",
    "candor", "candy", "cannon", "canoe", "canopy", "canter", "canvas",
    "canyon", "cape", "caper", "captain", "caramel", "caravan", "cardinal",
    "carnival", "carousel", "carriage", "carrot", "cartwheel", "cascade",
    "cask", "castanet", "castle", "cathedral", "cauldron", "cavalry",
    "cavern", "cedar", "celery", "cellar", "cello", "chalk", "chamber",
    "chapel", "charm", "cherry", "chestnut", "chime", "chimney", "chisel",
    "cider", "cinder", "circus", "citadel", "citrus", "clam", "clay",
    "cliff", "cloak", "clock", "cloud", "clover", "coast", "cobalt",
    "cobble", "cocoa", "coconut", "comet", "compass", "copper", "coral",
    "cork", "cottage", "cotton", "cove", "coyote", "crab", "cradle",
    "crane", "crater", "creek", "crescent", "cricket", "crow", "crown",
    "crumb", "crystal", "cuckoo", "cupboard", "current", "curtain",
    "cushion", "cypress", "daffodil", "dagger", "dahlia", "dairy", "daisy",
    "dale", "damask", "damsel", "damson", "dancer", "dandelion", "dapple",
    "dart", "dawn", "daydream", "dazzle", "decoy", "deer", "delight",
    "delta", "den", "denim", "desert", "destiny", "dew", "dewdrop",
    "diadem", "dial", "diamond", "dime", "dinghy", "dingo", "dipper",
    "ditch", "diver", "dock", "dolphin", "dome", "domino", "donkey",
    "doorway", "dormouse", "dove", "dragon", "dragonfly", "dragoon",
    "drake", "drawbridge", "dream", "drift", "drizzle", "drum", "duchess",
    "duck", "duet", "dune", "dusk", "dust", "dwelling", "dynamo", "eagle",
    "earth", "easel", "ebony", "echo", "eclipse", "eddy", "eel", "egret",
    "elbow", "elder", "elixir", "elk", "elm", "embassy", "ember", "emblem",
    "emerald", "empire", "emporium", "enchantment", "encore", "endive",
    "engine", "enigma", "envoy", "epic", "equinox", "ermine", "errand",
    "escape", "estate", "estuary", "evening", "evergreen", "ewe", "exile",
    "expanse", "explorer", "eyrie", "fable", "fairy", "falcon", "falls",
    "fawn", "feast", "feather", "fence", "fern", "ferry", "festival",
    "fiddle", "field", "fig", "finch", "fir", "fireside", "fjord", "flagon",
    "flame", "flannel", "flask", "fleece", "flint", "flock", "flower",
    "flute", "foal", "fog", "folly", "foothill", "forest", "forge",
    "fortune", "fossil", "fountain", "fox", "fresco", "frigate", "fringe",
    "frog", "frost", "gable", "galaxy", "gale", "galleon", "gallop",
    "garden", "garland", "garnet", "gate", "gazelle", "gecko", "gem",
    "geyser", "giant", "ginger", "glacier", "glade", "gleam", "glen",
    "glimmer", "globe", "glove", "goat", "goblet", "gold", "goose", "gorge",
    "gourd", "grain", "granite", "grape", "grass", "gravel", "griffin",
    "haddock", "hail", "halo", "hamlet", "hammer", "hammock", "harbor",
    "hare", "harp", "harvest", "hatchet", "haven", "hawk", "hay", "hazel",
    "hearth", "heather", "hedge", "hedgehog", "helm", "hemlock", "herald",
    "heron", "hickory", "hill", "hive", "hollow", "holly", "homestead",
    "honey", "hood", "hoof", "horizon", "horn", "horse", "hound",
    "hummingbird", "hunter", "hut", "ibex", "ibis", "ice", "iceberg",
    "icicle", "idol", "idyll", "igloo", "iguana", "illusion", "image",
    "imp", "impulse", "incense", "indigo", "infinity", "ingot", "ink",
    "inkwell", "inlet", "inn", "innkeeper", "insect", "inspiration",
    "instinct", "interlude", "invention", "iris", "iron", "island", "isle",
    "isotope", "isthmus", "itinerary", "ivory", "ivy", "jackal", "jade",
    "jaguar", "jamboree", "jar", "jasper", "jewel", "journey", "jungle",
    "kale", "kayak", "keel", "keep", "kelp", "kernel", "kettle", "kindle",
    "kingdom", "kitten", "labyrinth", "lace", "ladder", "lagoon", "lake",
    "lamb", "lamp", "lance", "landmark", "lantern", "lark", "lattice",
    "laurel", "lavender", "lea", "leather", "ledge", "legend", "lemon",
    "lichen", "lighthouse", "lightning", "lilac", "lily", "lime",
    "limestone", "linen", "lion", "locket", "lodge", "loom", "lullaby",
    "mackerel", "madrigal", "magnet", "magpie", "mallard", "mammoth",
    "mane", "mango", "manor", "mantle", "map", "maple", "marble", "march",
    "mare", "marigold", "marina", "marrow", "marsh", "mason", "mast",
    "meadow", "meadowlark", "medal", "melody", "melon", "mermaid", "mesa",
    "meteor", "mica", "midnight", "mill", "millstone", "minstrel", "mint",
    "mirror", "mist", "mitten", "moat", "monarch", "monk", "moon", "moor",
    "moose", "morning", "mosaic", "moss", "moth", "mountain", "muffin",
    "mulberry", "mural", "musket", "mustard", "myrtle", "mystery", "nail",
    "napkin", "narwhal", "navy", "nectar", "needle", "nest", "nettle",
    "newt", "nickel", "night", "nightingale", "nimble", "noble", "nomad",
    "noodle", "north", "notch", "nougat", "nugget", "nursery", "nutmeg",
    "oak", "oasis", "oat", "oboe", "obsidian", "ocean", "octave", "octopus",
    "olive", "onyx", "opal", "orange", "orbit", "orca", "orchard", "orchid",
    "organ", "oriole", "osprey", "otter", "outpost", "oven", "owl",
    "oyster", "ozone", "paddle", "paddock", "pagoda", "palace", "palm",
    "pancake", "panda", "panther", "paper", "parade", "parasol", "parcel",
    "parchment", "parrot", "parsley", "pasture", "patch", "path",
    "pavilion", "peach", "peacock", "peak", "pear", "pearl", "pebble",
    "pecan", "pelican", "pendant", "pennant", "penny", "peony", "pepper",
    "perch", "periwinkle", "petal", "pheasant", "piano", "pickle", "picnic",
    "pier", "pigeon", "pilgrim", "pillar", "pillow", "pilot", "pine",
    "pinecone", "pioneer", "pipe", "pirate", "pistachio", "pitcher",
    "pixie", "plain", "planet", "plank", "plateau", "plover", "plum",
    "plume", "pocket", "pod", "polar", "pomegranate", "pond", "pony",
    "poppy", "porch", "porcupine", "port", "potter", "pouch", "prairie",
    "prism", "prong", "pudding", "puddle", "puffin", "pumpkin", "puppet",
    "puzzle", "quail", "quarry", "quartz", "quill", "quiver", "rabbit",
    "raccoon", "racket", "radiance", "radish", "raft", "rafter", "rain",
    "rainbow", "raindrop", "raisin", "ramble", "rambler", "rampart",
    "ranch", "range", "rapids", "rapier", "rattle", "raven", "ravine",
    "realm", "redwood", "reed", "reef", "regatta", "relic", "rhubarb",
    "rhyme", "ribbon", "riddle", "ridge", "ring", "ripple", "river", "robe",
    "robin", "rock", "rocket", "rodeo", "roof", "rook", "rooster", "root",
    "rope", "rose", "rosemary", "rowan", "ruby", "rudder", "rug", "ruin",
    "rumble", "rune", "rush", "rye", "saber", "sable", "saddle", "saffron",
    "saga", "sage", "sail", "sailor", "salamander", "salmon", "salt",
    "sanctuary", "sand", "sandal", "sapling", "sapphire", "sardine", "sash",
    "satchel", "satellite", "satin", "saucer", "savanna", "sawdust",
    "scallop", "scarf", "scarlet", "scepter", "schooner", "scone", "scribe",
    "scroll", "sculptor", "seagull", "seahorse", "seal", "seashore",
    "season", "seed", "sentinel", "sequoia", "serpent", "shadow", "shale",
    "shanty", "shark", "sheep", "shell", "shepherd", "shield", "shingle",
    "ship", "shore", "shovel", "shrub", "sickle", "sienna", "signal",
    "silk", "silver", "sketch", "skiff", "sky", "skylark", "slate", "sled",
    "sleet", "slipper", "sloop", "smoke", "snail", "snow", "sonnet",
    "sorrow", "soup", "spade", "spark", "sparrow", "spice", "spider",
    "spindle", "spire", "splinter", "sponge", "spoon", "spring", "spruce",
    "squall", "squirrel", "stable", "stag", "star", "starling", "statue",
    "steeple", "stem", "stone", "stork", "storm", "strawberry", "stream",
    "string", "sugar", "summer", "sundial", "sunflower", "sunset", "supper",
    "swallow", "swamp", "swan", "sweater", "swift", "sword", "sycamore",
    "syrup", "table", "tack", "tadpole", "talisman", "tallow", "tambourine",
    "tangle", "tapestry", "tar", "tavern", "teapot", "temple", "tent",
    "terrace", "thatch", "thimble", "thistle", "thorn", "thrush", "thunder",
    "tide", "tiger", "tile", "timber", "timberland", "tin", "toad",
    "toffee", "tomato", "tome", "topaz", "torch", "tortoise", "toucan",
    "tower", "trail", "trawler", "treasure", "trellis", "tributary",
    "trinket", "trolley", "trout", "trumpet", "tuba", "tulip", "tunnel",
    "turnip", "turquoise", "turtle", "twig", "twilight", "twine", "ukulele",
    "ultramarine", "umber", "umbrella", "umpire", "underbrush", "undertow",
    "unicorn", "unity", "universe", "upland", "uplift", "upstream",
    "urchin", "urn", "utopia", "vale", "valley", "valor", "vane", "vanilla",
    "vapor", "vault", "veil", "vellum", "velvet", "venture", "verge",
    "vessel", "vine", "vineyard", "violet", "waffle", "wagon", "walnut",
    "walrus", "wand", "wander", "warbler", "wasp", "water", "waterfall",
    "wave", "wax", "weasel", "weaver", "well", "whale", "wharf", "wheat",
    "wheel", "whisper", "whistle", "wicker", "wildflower", "willow", "wind",
    "window", "winter", "wolf", "wonder", "wool", "xylophone", "yacht",
    "yak", "yarrow", "yellow", "yeoman", "zebra", "zenith", "zephyr",
]
