export const ENGLISH_WORDS = [
    "acorn", "anchor", "apple", "arrow", "autumn", "badger", "banner",
    "barley", "basket", "beacon", "berry", "birch", "blanket", "blossom",
    "bramble", "breeze", "bridge", "brook", "bubble", "butter", "candle",
    "canyon", "castle", "cedar", "chalk", "cherry", "cinder", "cliff",
    "clover", "cobble", "copper", "cotton", "cradle", "crystal", "dagger",
    "daisy", "dawn", "desert", "dragon", "dream", "dusk", "eagle", "ember",
    "falcon", "feather", "fern", "field", "flame", "flint", "forest",
    "fortune", "fountain", "fox", "frost", "garden", "ginger", "glacier",
    "glimmer", "gold", "granite", "gravel", "hammer", "harbor", "harvest",
    "hazel", "heather", "hollow", "honey", "horizon", "hunter", "island",
    "ivory", "ivy", "jasper", "jewel", "journey", "kettle", "kingdom",
    "kitten", "ladder", "lantern", "lavender", "leather", "lemon",
    "lightning", "lily", "linen", "maple", "marble", "meadow", "meteor",
    "midnight", "mirror", "mist", "moon", "morning", "moss", "mountain",
    "needle", "nettle", "night", "oak", "ocean", "orchard", "otter",
    "owl", "paper", "pebble", "pepper", "petal", "pillow", "pine",
    "planet", "plum", "pocket", "pond", "poppy", "puddle", "quarry",
    "quartz", "quiver", "rabbit", "rain", "raven", "ribbon", "ridge",
    "river", "robin", "rocket", "rose", "rumble", "saddle", "sage",
    "salmon", "shadow", "shell", "shepherd", "silver", "sky", "slate",
    "smoke", "snow", "sparrow", "spark", "spider", "spring", "stone",
    "storm", "stream", "summer", "sunset", "swallow", "sword", "thimble",
    "thistle", "thorn", "thunder", "timber", "tower", "treasure", "tulip",
    "tunnel", "twilight", "valley", "velvet", "violet", "wander",
    "water", "wheat", "whisper", "willow", "wind", "window", "winter",
    "wolf", "wonder", "wool", "yarrow", "yellow", "zephyr", "amber",
    "basil", "bellow", "canter", "dapple", "echo", "fable", "gleam",
    "hearth", "jungle", "kindle", "lullaby", "marrow", "nimble",
    "riddle", "sorrow", "tangle", "umber", "vessel", "wicker",
]
