import type { NamesByGender } from "src/constants/markovNamePresets"

export const FANTASY_NAMES: NamesByGender = {
    male: [
        "Aedric", "Aeron", "Alaric", "Aldric", "Aldwin", "Alvaren", "Andric",
        "Arannis", "Arkon", "Arnoth", "Arvendel", "Auberon", "Baelgar",
        "Balren", "Balthor", "Barathor", "Bastian", "Beldric", "Belros",
        "Berric", "Borin", "Bramwell", "Brannoc", "Brennic", "Caddoc", "Cador",
        "Calder", "Caldor", "Caspian", "Cedran", "Cedrik", "Cormac", "Corvin",
        "Corvus", "Daelor", "Daemar", "Dagrim", "Darion", "Darvell", "Davor",
        "Delmar", "Dorian", "Dorvan", "Dravek", "Draven", "Drogan", "Dunstan",
        "Duran", "Eamon", "Edric", "Eldric", "Eldrin", "Elric", "Eltharion",
        "Emeric", "Erevan", "Eskar", "Evander", "Evrard", "Faelan", "Faelar",
        "Falken", "Faramond", "Farren", "Fendrel", "Fennick", "Fenrik",
        "Florian", "Galadrin", "Garrick", "Garron", "Garrow", "Gavric",
        "Gerrit", "Gideon", "Gorran", "Gorvath", "Grimward", "Hadrian", "Hakan",
        "Halden", "Haldor", "Halvric", "Harlan", "Harrow", "Hawthorn", "Idrin",
        "Ingram", "Ithron", "Ivor", "Jaelen", "Jarek", "Jareth", "Joren",
        "Jorvan", "Kaelen", "Kaeric", "Kaldris", "Kasimir", "Kaspar", "Keiran",
        "Kellan", "Kestrin", "Korrin", "Kovar", "Lathan", "Leofric", "Leoric",
        "Lorcan", "Lucan", "Lysander", "Maddoc", "Maelor", "Magnar", "Malcor",
        "Malric", "Marek", "Marrec", "Merrick", "Mordan", "Mordrin", "Morvran",
        "Nareth", "Nathrel", "Nerion", "Nevarre", "Nevin", "Norric", "Oberin",
        "Orinthal", "Orlan", "Orrin", "Orvan", "Oskar", "Osric", "Oswin",
        "Padrig", "Pellan", "Pelleas", "Perrin", "Pyrrus", "Quenril", "Quillon",
        "Radovan", "Ragnor", "Ralen", "Ravos", "Rendric", "Rhodric", "Rhydian",
        "Riordan", "Roderan", "Rolan", "Roran", "Rowell", "Rurik", "Saevar",
        "Sarek", "Sarvin", "Seldric", "Sevrin", "Soren", "Stellan", "Taliesin",
        "Talon", "Tarquin", "Tavian", "Teodric", "Thalion", "Tharivol",
        "Theodric", "Theron", "Tormar", "Tormund", "Torvald", "Tristan",
        "Uldor", "Ulfric", "Ulric", "Ulven", "Urien", "Uthar", "Vaelric",
        "Valdren", "Valen", "Vandrel", "Varek", "Varian", "Vaughn", "Vesmir",
        "Wendric", "Wolfric", "Wystan", "Xandor", "Xavian", "Yaren", "Yorick",
        "Zander", "Zarek", "Zoltan",
    ],
    female: [
        "Adria", "Aeliana", "Aelwen", "Aelyn", "Aerith", "Aislinn", "Alessia",
        "Althea", "Alyndra", "Amara", "Amarelle", "Annora", "Anwen", "Arabeth",
        "Aravel", "Aria", "Ariwyn", "Aurelle", "Aveline", "Azura", "Belara",
        "Belisande", "Branwen", "Brenna", "Brielle", "Briony", "Brisha",
        "Brynneth", "Caelira", "Caelynn", "Calanthe", "Calista", "Calla",
        "Cassia", "Celandine", "Celestra", "Ceridwen", "Cerys", "Coralie",
        "Corisande", "Cyrene", "Daelyra", "Dahlia", "Daria", "Dariel",
        "Delphine", "Delyra", "Eirlys", "Elandra", "Elara", "Elaria",
        "Elisande", "Elowen", "Elowyn", "Elspeth", "Elyndra", "Emberly",
        "Eryndel", "Esmera", "Evaine", "Evangeline", "Faelwen", "Faye",
        "Fayeth", "Fenella", "Feyra", "Fianna", "Fiorella", "Galathil",
        "Galena", "Genevra", "Gwendolen", "Gwenhael", "Gwyneth", "Halwyn",
        "Helaina", "Hesper", "Idony", "Ilaria", "Ilsabet", "Ilyana", "Imriel",
        "Iriel", "Isadora", "Isara", "Iselle", "Isolde", "Ithilwen", "Ivana",
        "Jalira", "Jessamine", "Jessira", "Kaela", "Kaelira", "Kalinda",
        "Kassia", "Katria", "Kiriel", "Larissa", "Leira", "Lethiel", "Linnea",
        "Liora", "Lirael", "Liriel", "Lorelai", "Lunara", "Lunette", "Lyra",
        "Lysanthe", "Lyssara", "Maelis", "Maelle", "Maerwen", "Maren",
        "Marisande", "Melisande", "Melora", "Meriel", "Mirabel", "Mireille",
        "Mirelda", "Morgana", "Morwen", "Myrelle", "Naelith", "Naeris",
        "Nerina", "Nerissa", "Nerys", "Nessa", "Niamh", "Nimra", "Nimue",
        "Nymeria", "Nysa", "Odile", "Olwen", "Ondine", "Ophira", "Oriane",
        "Oriel", "Orla", "Orlaith", "Perrine", "Quilla", "Raelith", "Rhiannel",
        "Rhiannon", "Rhoswen", "Rowenna", "Sabeth", "Saphira", "Sariel",
        "Selune", "Selvara", "Seraphel", "Seraphine", "Sevrina", "Shaelen",
        "Solenne", "Sorcha", "Sylvara", "Sylvie", "Talia", "Tamaris", "Taria",
        "Tavia", "Teleri", "Thalassa", "Thandra", "Thessaly", "Tindra",
        "Tirzah", "Ulyana", "Undine", "Vaelora", "Valeska", "Valora", "Velessa",
        "Venya", "Vesna", "Vianne", "Vivienne", "Wisteria", "Wynna", "Xyliel",
        "Yara", "Yllana", "Ynara", "Ysera", "Yseult", "Ysolde", "Yvaine",
        "Zaria", "Zefira", "Zelaine", "Zephyrine", "Zinnia", "Zora",
    ],
    neutral: [
        "Adair", "Aelis", "Aeris", "Aeryn", "Alaris", "Alder", "Ambrel",
        "Arden", "Ardyn", "Arin", "Arrow", "Ash", "Ashby", "Ashen", "Ashlin",
        "Aspen", "Astra", "Aurel", "Auren", "Averil", "Bellin", "Blaise",
        "Brenn", "Briar", "Brin", "Bryn", "Cael", "Caelith", "Cairn", "Calyx",
        "Cedar", "Ciel", "Cinder", "Corin", "Corrin", "Cove", "Dace", "Dael",
        "Darrow", "Del", "Dune", "Dusk", "Echo", "Eiren", "Elden", "Elin",
        "Elio", "Ellory", "Ember", "Emrys", "Eris", "Evren", "Fable", "Faelyn",
        "Faer", "Fallow", "Faolan", "Fenn", "Fern", "Finch", "Flint", "Flynn",
        "Galen", "Garnet", "Glade", "Glynn", "Halcyon", "Hale", "Hart", "Haven",
        "Heron", "Idris", "Ilex", "Indra", "Indri", "Ione", "Isen", "Isle",
        "Jae", "Jaren", "Jem", "Jory", "Juniper", "Kade", "Kael", "Kaelan",
        "Kellis", "Kerris", "Kestrel", "Kiran", "Lael", "Laken", "Lark",
        "Larkin", "Linden", "Lior", "Lirien", "Lorn", "Lumen", "Lumi", "Lyr",
        "Lyric", "Mael", "Maris", "Marlow", "Merrin", "Merrow", "Mica",
        "Mirren", "Mistral", "Morrow", "Moss", "Nael", "Nairn", "Nevan", "Neve",
        "Nim", "Noor", "Nova", "Nym", "Nyx", "Oakes", "Onyx", "Oren", "Ossian",
        "Pax", "Pell", "Pike", "Quen", "Quill", "Quinlan", "Quinn", "Rain",
        "Raine", "Raven", "Reeve", "Ren", "Revel", "Reyn", "Rhys", "Riel",
        "Rill", "Riven", "Rook", "Rowan", "Rue", "Rune", "Sable", "Sael",
        "Saelwyn", "Sayer", "Selwyn", "Sennet", "Shae", "Shale", "Silver",
        "Sky", "Sloane", "Sol", "Solace", "Sorin", "Sorrel", "Sparrow", "Storm",
        "Sylas", "Talis", "Tallis", "Tallow", "Tamsin", "Tarn", "Taryn",
        "Teague", "Teal", "Thane", "Thistle", "Thorne", "Tiern", "Tirael",
        "Tovin", "Ulys", "Umber", "Umbra", "Vael", "Val", "Vale", "Vesper",
        "Vireo", "Wilder", "Winter", "Wisp", "Wren", "Wyn", "Wynn", "Xen",
        "Yael", "Yarrow", "Zael", "Zale", "Zephyr", "Zinn",
    ],
}
