import type { NamesByGender } from "src/constants/markovNamePresets"

const GREEK_MALE_NAMES = [
    "Achilleas", "Achilles", "Adonis", "Adrastos", "Agamemnon", "Agathon",
    "Aias", "Aigeus", "Aineias", "Aiolos", "Aischylos", "Akakios", "Alexandros",
    "Alkaios", "Alkibiades", "Alkinoos", "Ambrosios", "Anatolios", "Anaxagoras",
    "Anaximandros", "Andreas", "Andronikos", "Angelos", "Antiochos", "Antonios",
    "Apollodoros", "Apostolos", "Archimedes", "Aristarchos", "Aristides",
    "Aristophanes", "Aristoteles", "Arkadios", "Athanasios", "Athenagoras",
    "Bion", "Charalambos", "Charilaos", "Chariton", "Christos", "Chrysanthos",
    "Damianos", "Damon", "Dareios", "Demetrios", "Demokritos", "Demosthenes",
    "Dimitris", "Diogenes", "Diomedes", "Dionysios", "Dorotheos", "Drakon",
    "Efstathios", "Ektoras", "Emmanouil", "Empedokles", "Epaminondas",
    "Epikouros", "Eratosthenes", "Euklides", "Euripides", "Eustratios",
    "Evagoras", "Evangelos", "Evdokimos", "Fotis", "Georgios", "Gerasimos",
    "Gregorios", "Hektor", "Herakles", "Hermes", "Hesiodos", "Hippokrates",
    "Hippolytos", "Homeros", "Iakovos", "Iason", "Ikaros", "Ilias", "Ioannis",
    "Iraklis", "Isidoros", "Isokrates", "Kalchas", "Kallias", "Kallikrates",
    "Kallimachos", "Kimon", "Kleisthenes", "Kleon", "Konstantinos", "Kosmas",
    "Kostas", "Kyprianos", "Kyriakos", "Kyros", "Laertes", "Lambros",
    "Leandros", "Leon", "Leonidas", "Leontios", "Linos", "Loukas", "Lykaon",
    "Lykourgos", "Lysandros", "Lysimachos", "Makarios", "Markos", "Meletios",
    "Menandros", "Menelaos", "Menon", "Michalis", "Miltiades", "Nearchos",
    "Nektarios", "Neoptolemos", "Nestor", "Nikandros", "Nikephoros", "Nikias",
    "Nikodemos", "Nikolaos", "Nikomedes", "Nikos", "Odysseus", "Onesimos",
    "Orestes", "Panagiotis", "Panos", "Pantelis", "Paris", "Parmenides",
    "Patroklos", "Pausanias", "Pavlos", "Pelops", "Periandros", "Pericles",
    "Perseus", "Petros", "Philemon", "Philippos", "Philon", "Photios",
    "Pindaros", "Platon", "Polydoros", "Polykarpos", "Praxiteles", "Prokopios",
    "Prometheus", "Protagoras", "Ptolemaios", "Pyrrhos", "Pythagoras",
    "Sarantis", "Simonides", "Sokratis", "Solon", "Sophokles", "Sotirios",
    "Spyridon", "Spyros", "Stamatis", "Stathis", "Stavros", "Stefanos",
    "Stelios", "Strabon", "Takis", "Telemachos", "Thales", "Thanos",
    "Themistokles", "Theodoros", "Theophilos", "Theophrastos", "Theseus",
    "Thoukydides", "Thrasyvoulos", "Timoleon", "Timon", "Timotheos",
    "Triantafyllos", "Tryfon", "Vangelis", "Vasilios", "Xanthos", "Xenokrates",
    "Xenophon", "Yannis", "Zacharias", "Zenobios", "Zenon", "Zisis",
]
const GREEK_FEMALE_NAMES = [
    "Adamantia", "Aethra", "Agapi", "Agathe", "Aglaia", "Aglaopi", "Aikaterini",
    "Alexandra", "Alexia", "Alkestis", "Alkmene", "Alkyone", "Althaia",
    "Amalia", "Amphitrite", "Anastasia", "Andriana", "Andromache", "Andromeda",
    "Angeliki", "Antheia", "Anthi", "Anthoula", "Antigone", "Aphrodite",
    "Areti", "Aretousa", "Argyro", "Ariadne", "Arsinoe", "Artemis", "Asimina",
    "Aspasia", "Atalante", "Athena", "Berenike", "Calliope", "Chara",
    "Charikleia", "Chloe", "Chrysa", "Chrysanthe", "Chryseis", "Chrysoula",
    "Danae", "Danai", "Daphne", "Despina", "Dimitra", "Dione", "Doris",
    "Dorothea", "Efthymia", "Eftychia", "Eirini", "Electra", "Eleftheria",
    "Eleni", "Eleonora", "Elissavet", "Elpida", "Eos", "Erato", "Eudokia",
    "Eugenia", "Eunike", "Euphrosyne", "Eurydice", "Eurynome", "Euterpe",
    "Evadne", "Evangelia", "Evanthia", "Evgenia", "Foteini", "Galateia",
    "Galini", "Georgia", "Glykeria", "Harmonia", "Hebe", "Hera", "Hermione",
    "Hestia", "Hippolyta", "Hypatia", "Ianthe", "Ino", "Io", "Ioanna",
    "Iokaste", "Iola", "Iphigenia", "Irini", "Iris", "Ismene", "Kallirhoe",
    "Kalliroi", "Kallisti", "Kallisto", "Kalypso", "Kassandra", "Kassiani",
    "Katerina", "Kleio", "Kleopatra", "Klytaimnestra", "Konstantina", "Kore",
    "Kynthia", "Kyriaki", "Kyveli", "Lamia", "Leda", "Lefkothea", "Lemonia",
    "Leto", "Lito", "Lydia", "Lysandra", "Lysistrata", "Maia", "Makaria",
    "Maria", "Marianthi", "Marina", "Medea", "Melanthe", "Melina", "Melissa",
    "Melpomene", "Merope", "Metis", "Mnemosyne", "Myrrine", "Myrsini", "Myrto",
    "Nausicaa", "Nefeli", "Nephele", "Niki", "Niobe", "Nyx", "Olympia",
    "Olympias", "Ourania", "Pagona", "Panagiota", "Pandora", "Panthea",
    "Paraskevi", "Parthena", "Pasiphae", "Pelagia", "Penelope", "Persephone",
    "Phaedra", "Philomela", "Phoebe", "Polymnia", "Polyxena", "Pothiti",
    "Psyche", "Rhea", "Rodanthi", "Rodope", "Roxani", "Sappho", "Selene",
    "Semeli", "Sofia", "Sophrosyne", "Sotiria", "Stamatia", "Stavroula",
    "Stella", "Stephania", "Styliani", "Tatiana", "Terpsichore", "Thaleia",
    "Thalia", "Theano", "Thekla", "Theodora", "Theodosia", "Theoni",
    "Theophano", "Thetis", "Timandra", "Triantafyllia", "Vaia", "Vasiliki",
    "Xanthe", "Xanthippe", "Xeni", "Zacharoula", "Zenobia", "Zinovia", "Zoe",
]
export const GREEK_NAMES: NamesByGender = {
    male: GREEK_MALE_NAMES,
    female: GREEK_FEMALE_NAMES,
    neutral: [...GREEK_MALE_NAMES, ...GREEK_FEMALE_NAMES],
}
