import type { NamesByGender } from "src/constants/markovNamePresets"

export const JAPANESE_NAMES: NamesByGender = {
    male: [
        "Akihiro", "Akihito", "Akinori", "Akio", "Akiyoshi", "Arata", "Atsuo",
        "Atsushi", "Daichi", "Daigo", "Daiki", "Daisaku", "Daisuke", "Eiichi",
        "Eiji", "Eisuke", "Fumihiro", "Fumio", "Genji", "Gentaro", "Goichi",
        "Goro", "Hachiro", "Hajime", "Haruki", "Haruto", "Hayao", "Hayate",
        "Hayato", "Heisuke", "Hideaki", "Hideki", "Hideo", "Hidetoshi",
        "Hikoichi", "Hiroaki", "Hirofumi", "Hiroki", "Hironori", "Hiroshi",
        "Hiroto", "Hisao", "Hisashi", "Hisato", "Ichiro", "Ikki", "Ippei",
        "Isamu", "Isao", "Isshin", "Jinpei", "Jiro", "Joji", "Junichi", "Junya",
        "Kaito", "Kanji", "Kanta", "Katsuhiko", "Katsuo", "Katsuro", "Kazuki",
        "Kazuo", "Kazuya", "Keigo", "Keiichi", "Keisuke", "Keita", "Kenichi",
        "Kenji", "Kenshin", "Kenta", "Kentaro", "Kenzo", "Kichiro", "Kimio",
        "Kiyoshi", "Kiyotaka", "Kohei", "Koichi", "Koji", "Kojiro", "Kosuke",
        "Kota", "Kotaro", "Kunio", "Kyohei", "Makio", "Mamoru", "Manabu",
        "Masahiro", "Masaki", "Masanori", "Masao", "Masaru", "Masashi",
        "Masato", "Masayuki", "Michihiro", "Michio", "Mikio", "Minato",
        "Minoru", "Mitsuhiro", "Mitsuo", "Mitsuru", "Morio", "Motoki",
        "Munenori", "Naoki", "Naoto", "Noboru", "Nobuhiro", "Nobuo", "Nobuyuki",
        "Noriaki", "Norihiro", "Norio", "Osamu", "Renji", "Rentaro", "Riku",
        "Rikuto", "Rokuro", "Ryohei", "Ryoichi", "Ryoma", "Ryosuke", "Ryota",
        "Ryuichi", "Ryuji", "Ryunosuke", "Ryusei", "Saburo", "Sadao", "Satoru",
        "Satoshi", "Seiichi", "Seiji", "Shigeru", "Shingo", "Shinichi",
        "Shinji", "Shintaro", "Shinya", "Shiro", "Shohei", "Shota", "Shuichi",
        "Shunji", "Shunsuke", "Soichiro", "Sojiro", "Sosuke", "Souta", "Susumu",
        "Tadao", "Tadashi", "Taichi", "Taiga", "Takahiro", "Takanori",
        "Takashi", "Takayuki", "Takehiko", "Takeru", "Takeshi", "Takumi",
        "Takuya", "Tamotsu", "Taro", "Tatsuya", "Teruo", "Tetsuo", "Tetsuya",
        "Tokio", "Tokuma", "Tomohiro", "Toru", "Toshiaki", "Toshio", "Toshiro",
        "Tsutomu", "Tsuyoshi", "Yamato", "Yasuhiro", "Yasuo", "Yasushi",
        "Yoichi", "Yoshiaki", "Yoshinori", "Yoshio", "Yoshiro", "Yosuke",
        "Yuichi", "Yukio", "Yusuke", "Yuta", "Yuto", "Zenjiro",
    ],
    female: [
        "Aiko", "Akane", "Akemi", "Akiko", "Ami", "Anzu", "Asako", "Asami",
        "Asuka", "Atsuko", "Aya", "Ayaka", "Ayako", "Ayame", "Ayane", "Ayano",
        "Ayumi", "Chiaki", "Chie", "Chieko", "Chiharu", "Chika", "Chinatsu",
        "Chiyo", "Chiyoe", "Chiyoko", "Chizuru", "Eiko", "Emi", "Emiko", "Eri",
        "Erika", "Etsuko", "Fujiko", "Fumiko", "Fuyuko", "Hanae", "Hanako",
        "Harue", "Haruka", "Haruko", "Haruna", "Hatsue", "Hideko", "Hina",
        "Hinako", "Hiroko", "Hisae", "Hisako", "Hitomi", "Honoka", "Hotaru",
        "Ikue", "Ikuko", "Junko", "Kana", "Kanae", "Kanako", "Kanon", "Kaori",
        "Karin", "Kasumi", "Kayo", "Kazue", "Kazuko", "Keiko", "Kiku", "Kimie",
        "Kimiko", "Kinu", "Kinuko", "Kiyoko", "Koharu", "Kotomi", "Kotone",
        "Kozue", "Kumi", "Kumiko", "Kyoka", "Kyoko", "Machiko", "Madoka", "Mai",
        "Maiko", "Maki", "Makiko", "Mami", "Mana", "Manami", "Marika", "Mariko",
        "Masae", "Masako", "Matsuko", "Mayu", "Mayumi", "Megumi", "Mei",
        "Michiko", "Michiyo", "Midori", "Mie", "Mieko", "Miho", "Mihoko",
        "Mika", "Miki", "Mina", "Minako", "Minami", "Mio", "Misa", "Misaki",
        "Mitsue", "Mitsuko", "Miwa", "Miyako", "Miyoko", "Miyu", "Miyuki",
        "Mizue", "Momoe", "Momoka", "Momoko", "Nagiko", "Nami", "Nana",
        "Nanako", "Nanami", "Naoko", "Natsuko", "Natsumi", "Nobuko", "Nodoka",
        "Noriko", "Nozomi", "Reika", "Reiko", "Reina", "Remi", "Rie", "Rika",
        "Riko", "Rina", "Risa", "Ritsuko", "Ruri", "Ryoko", "Sachie", "Sachiko",
        "Sae", "Saki", "Sakiko", "Sakura", "Sanae", "Satoko", "Sayaka",
        "Sayoko", "Sayuri", "Seiko", "Setsuko", "Shigeko", "Shiori", "Shizue",
        "Shizuka", "Shoko", "Sonoko", "Sumiko", "Suzu", "Suzume", "Takako",
        "Tamae", "Tamiko", "Teruko", "Tokiko", "Tomoe", "Tomoka", "Tomoko",
        "Toshiko", "Tsubame", "Tsukiko", "Tsuru", "Umeko", "Wakana", "Yae",
        "Yasuko", "Yayoi", "Yoko", "Yoshie", "Yoshiko", "Yui", "Yukari",
        "Yukie", "Yukiko", "Yumi", "Yumiko", "Yuna", "Yuri", "Yuriko", "Yuzuha",
    ],
    neutral: [
        "Aimi", "Akari", "Akatsuki", "Aki", "Akimi", "Akira", "Akito", "Amane",
        "Aoba", "Aoi", "Asa", "Asagi", "Asahi", "Asumi", "Ayase", "Ayumu",
        "Chiaya", "Chihaya", "Chihiro", "Eiri", "Enji", "Fumi", "Fuuka", "Fuyu",
        "Haru", "Haruhi", "Harumi", "Hayami", "Hayase", "Hibiki", "Hijiri",
        "Hikari", "Hikaru", "Hinami", "Hinata", "Hinode", "Hiro", "Hiromi",
        "Hisa", "Hisami", "Hiyori", "Homura", "Hotaka", "Ibuki", "Ichika",
        "Iku", "Inori", "Iori", "Iroha", "Isami", "Itsuki", "Izumi", "Izumo",
        "Jin", "Jun", "Kaede", "Kagari", "Kagura", "Kai", "Kairi", "Kanade",
        "Kaname", "Kanata", "Kaoru", "Kasane", "Katsumi", "Kazane", "Kazu",
        "Kazuha", "Kazumi", "Kei", "Kira", "Kiri", "Kiyo", "Kiyomi", "Kiyora",
        "Kohaku", "Kokoro", "Koto", "Kotori", "Kou", "Kurenai", "Kurumi", "Kyo",
        "Mahiro", "Mahiru", "Maho", "Makoto", "Mao", "Masa", "Masami", "Masumi",
        "Matsuri", "Michi", "Michiru", "Miharu", "Mihiro", "Mikado", "Mikaze",
        "Mikoto", "Minori", "Mirai", "Mitsu", "Mitsuki", "Miyabi", "Mizuho",
        "Mizuki", "Nagare", "Nagi", "Nagisa", "Nanaho", "Nanase", "Nao",
        "Naomi", "Natsu", "Natsuki", "Nishiki", "Noa", "Nozomu", "Rai", "Ran",
        "Rei", "Ren", "Reo", "Rikka", "Rin", "Rinne", "Rio", "Rui", "Ruka",
        "Ryo", "Ryuu", "Sachi", "Sakae", "Saku", "Sakuya", "Sango", "Satomi",
        "Sayo", "Sei", "Seika", "Sena", "Seren", "Shiki", "Shima", "Shin",
        "Shinobu", "Shion", "Shizuku", "Sho", "Shuu", "Soma", "Sora", "Sou",
        "Subaru", "Sui", "Sumi", "Suzuka", "Tadami", "Taiki", "Taka", "Takami",
        "Tamaki", "Tatsumi", "Tenka", "Tenma", "Tohru", "Toki", "Tomo",
        "Tomomi", "Toshimi", "Towa", "Tsubaki", "Tsubasa", "Tsubomi", "Tsukasa",
        "Tsuki", "Tsukushi", "Tsumugi", "Umi", "Uta", "Waka", "Wakaba", "Yasu",
        "Yori", "Yoru", "Yoshi", "Yoshimi", "Yu", "Yuka", "Yuki", "Yukimi",
        "Yuma", "Yume", "Yuu", "Yuuki", "Yuzu", "Yuzuki", "Yuzuriha", "Zen",
    ],
}
