import type { NamesByGender } from "src/constants/markovNamePresets"

const LATIN_MALE_NAMES = [
    "Acilius", "Aelianus", "Aemilius", "Aetius", "Agricola", "Agrippa",
    "Ahenobarbus", "Albanus", "Albinus", "Ambrosius", "Amulius", "Ancus",
    "Anicius", "Annaeus", "Antoninus", "Antonius", "Apollinaris", "Appius",
    "Aquila", "Asinius", "Atticus", "Augustinus", "Augustus", "Aulus",
    "Aurelianus", "Aurelius", "Ausonius", "Avitus", "Balbus", "Bassus",
    "Blandus", "Boethius", "Brutus", "Caecilius", "Caelius", "Caesar", "Caius",
    "Calidus", "Calpurnius", "Calvus", "Camillus", "Canus", "Capito", "Carus",
    "Cassianus", "Cassius", "Cato", "Catullus", "Celsus", "Censorinus",
    "Cicero", "Cincinnatus", "Claudianus", "Claudius", "Clemens", "Cocles",
    "Columella", "Constantinus", "Cornelius", "Corvinus", "Cotta", "Crassus",
    "Crispus", "Curio", "Cyprianus", "Decimus", "Decius", "Dentatus", "Didius",
    "Diocletianus", "Domitianus", "Domitius", "Drusus", "Egnatius", "Ennius",
    "Eutropius", "Fabius", "Fabricius", "Faustus", "Festus", "Firmus",
    "Flaccus", "Flavius", "Florus", "Fronto", "Fulvius", "Gaius", "Galba",
    "Gallienus", "Gallus", "Gellius", "Geminus", "Germanicus", "Gnaeus",
    "Gordianus", "Gracchus", "Gratianus", "Hadrianus", "Helvius", "Herennius",
    "Hilarius", "Horatius", "Hortensius", "Hostilius", "Julianus", "Julius",
    "Junius", "Justus", "Juvenalis", "Labienus", "Lactantius", "Laelius",
    "Laurentius", "Lentulus", "Lepidus", "Livius", "Longinus", "Lucanus",
    "Lucius", "Lucretius", "Lucullus", "Macrinus", "Maecenas", "Magnus",
    "Mamercus", "Manius", "Marcellus", "Marcianus", "Marcus", "Marius",
    "Martialis", "Maximianus", "Maximus", "Messala", "Metellus", "Naso",
    "Nepos", "Nero", "Nerva", "Nonius", "Numa", "Numerius", "Octavianus",
    "Octavius", "Opimius", "Otho", "Ovidius", "Papirius", "Paulinus", "Paulus",
    "Pertinax", "Petronius", "Piso", "Pius", "Plautus", "Plinius", "Pollio",
    "Pompeius", "Porcius", "Postumus", "Priscus", "Probus", "Publius",
    "Quintilianus", "Quintus", "Regulus", "Remus", "Rufinus", "Rufus",
    "Sabinus", "Sallustius", "Scaevola", "Scipio", "Secundus", "Sempronius",
    "Seneca", "Septimus", "Sergius", "Servius", "Severianus", "Severus",
    "Sextus", "Silius", "Silvanus", "Spurius", "Statius", "Sulla", "Tacitus",
    "Tertius", "Tiberius", "Titus", "Traianus", "Tullius", "Valens", "Valerius",
    "Varro", "Verus", "Vespasianus", "Vibius", "Vitellius",
]
const LATIN_FEMALE_NAMES = [
    "Acilia", "Aebutia", "Aelia", "Aemilia", "Aemiliana", "Afrania",
    "Agrippina", "Albia", "Albina", "Ancharia", "Annia", "Antistia", "Antonia",
    "Appia", "Apronia", "Aquilia", "Aquilina", "Arrecina", "Arria", "Asinia",
    "Atia", "Atilia", "Augusta", "Aurelia", "Aurora", "Aurunculeia", "Avita",
    "Balbina", "Blandina", "Caecilia", "Caeciliana", "Caelia", "Caesonia",
    "Calpurnia", "Calvina", "Camilla", "Canuleia", "Carvilia", "Cassia",
    "Catia", "Celsa", "Cincia", "Claudia", "Clementia", "Cloatia", "Clodia",
    "Cloelia", "Coelia", "Cominia", "Constantia", "Cornelia", "Crispa",
    "Crispina", "Curia", "Decima", "Didia", "Domitia", "Domitilla", "Drusilla",
    "Egnatia", "Fabia", "Fabiola", "Fausta", "Faustilla", "Faustina",
    "Flaminia", "Flavia", "Florentia", "Fonteia", "Fulvia", "Fundania",
    "Galeria", "Galla", "Gavia", "Gellia", "Gemina", "Gratia", "Gratiana",
    "Hadriana", "Helvia", "Herennia", "Hilaria", "Honoria", "Horatia",
    "Hortensia", "Hostilia", "Julia", "Julilla", "Junia", "Justina", "Juventia",
    "Laelia", "Laurentia", "Lavinia", "Lepida", "Licinia", "Livia", "Livilla",
    "Lollia", "Longina", "Lucia", "Lucilla", "Lucina", "Lucretia", "Macrina",
    "Maecia", "Mamilia", "Manlia", "Marcella", "Marcellina", "Marcia",
    "Marciana", "Martia", "Maxima", "Memmia", "Messalina", "Minervina",
    "Minicia", "Mucia", "Munatia", "Naevia", "Nigidia", "Nonia", "Novella",
    "Numeria", "Octavia", "Oppia", "Orbiana", "Papiria", "Paulina", "Petronia",
    "Placidia", "Plautia", "Plotina", "Pompeia", "Pompilia", "Pomponia",
    "Popillia", "Poppaea", "Porcia", "Postumia", "Prima", "Prisca", "Priscilla",
    "Quinctia", "Quintilla", "Quintina", "Rubria", "Rufina", "Rutilia",
    "Sabina", "Salonina", "Salvia", "Scantia", "Scribonia", "Secunda",
    "Sempronia", "Sentia", "Septima", "Sergia", "Servilia", "Severa",
    "Severina", "Sextilia", "Silvia", "Sosia", "Statilia", "Stertinia",
    "Sulpicia", "Tarquinia", "Terentia", "Tertia", "Tertulla", "Tiberia",
    "Titia", "Titiana", "Trebonia", "Tuccia", "Tullia", "Ulpia", "Urbica",
    "Valentina", "Valeria", "Valeriana", "Varia", "Vellia", "Verania",
    "Vergilia", "Verginia", "Vespasia", "Vestilia", "Vettia", "Vibia",
    "Vibidia", "Vinicia", "Vipsania", "Vitalia", "Vitellia", "Volumnia",
    "Volusia",
]
export const LATIN_NAMES: NamesByGender = {
    male: LATIN_MALE_NAMES,
    female: LATIN_FEMALE_NAMES,
    neutral: [...LATIN_MALE_NAMES, ...LATIN_FEMALE_NAMES],
}
