import type { NamesByGender } from "src/constants/markovNamePresets"

const MORDOR_MALE_NAMES = [
    "Agdush", "Akrum", "Azbuk", "Azgrak", "Azog", "Badgash", "Baghrok",
    "Bagronk", "Bagrot", "Balgrum", "Bashnag", "Blodrag", "Bogrum", "Bolg",
    "Bolgath", "Bolgrat", "Borgul", "Borzag", "Brugash", "Bruzg", "Buzgrot",
    "Dagrok", "Dakrul", "Dargoth", "Doglub", "Dragnak", "Drogmash", "Drubak",
    "Dugbur", "Dugrak", "Durbag", "Durgash", "Durgol", "Durzak", "Dushnak",
    "Dushrok", "Fangrak", "Fargol", "Gashnak", "Gashrak", "Gazmug", "Ghashbur",
    "Ghazbur", "Ghorbash", "Glarzug", "Gludrak", "Gnarlug", "Golfimbul",
    "Gorbag", "Gorgath", "Gorlug", "Gorzag", "Gorzul", "Gothmog", "Gozbag",
    "Grakdush", "Grakk", "Grashbag", "Grashnak", "Grimbak", "Grimzak",
    "Grishnakh", "Grobag", "Grobnak", "Grodush", "Grolbag", "Gromsh", "Gronk",
    "Grubdush", "Grubnak", "Gruzbag", "Gruzzak", "Guldush", "Gulrak", "Gulzog",
    "Haggak", "Hakdush", "Hazbrak", "Horgash", "Hrulgash", "Hurzag", "Kagrat",
    "Kargath", "Karguk", "Karzug", "Kazgrob", "Khrosh", "Krashnak", "Krogbag",
    "Krugdush", "Krugnak", "Kruk", "Kuldrag", "Kulgash", "Lagduf", "Lagdush",
    "Lagrok", "Lugbash", "Lugdush", "Lugnak", "Lugrot", "Lurgash", "Lurtz",
    "Magbuk", "Magrok", "Maugrash", "Mauhur", "Mauzgul", "Mogdush", "Mograth",
    "Morbag", "Mozgul", "Mugdush", "Mugrak", "Murzag", "Muzdrak", "Muzgash",
    "Muzgur", "Nagrub", "Narbag", "Nargash", "Nargul", "Narzug", "Nazgob",
    "Nuzgash", "Ogbur", "Ogdrak", "Oggrim", "Olgdush", "Olgrak", "Orbag",
    "Orgrath", "Orzag", "Prugash", "Pugrash", "Radbug", "Ragduf", "Ragrok",
    "Rakdush", "Ratbag", "Rugbash", "Rugdak", "Ruzdrak", "Ruzgash", "Shagbur",
    "Shagdush", "Shagrak", "Shagrat", "Shakhbur", "Shazgul", "Shazrok",
    "Shrakdush", "Shuzgul", "Skagdush", "Skarn", "Skorg", "Skrag", "Snaga",
    "Snagdush", "Snagrat", "Snarlug", "Snurg", "Thakrum", "Thragash",
    "Throgdush", "Throk", "Thrugbag", "Thrugg", "Tugrak", "Tuzgash", "Ubrak",
    "Ufthak", "Ugbash", "Ugdush", "Ughlak", "Ugluk", "Ugrak", "Ukbar", "Ukdrag",
    "Uldush", "Ulgash", "Ulgrok", "Urbag", "Urgash", "Uzbak", "Uzgrot",
    "Vargdush", "Varguk", "Vorgash", "Vorgrak", "Vugrak", "Vurbag", "Yagbur",
    "Yagduk", "Yazgrob", "Yazhnak", "Zagbash", "Zogrim", "Zugrak", "Zurgash",
]
const MORDOR_FEMALE_NAMES = [
    "Agra", "Agrisha", "Azash", "Azgra", "Azgrisha", "Azka", "Badga", "Bagra",
    "Bashka", "Bashra", "Blodra", "Bogra", "Bolgish", "Bolgra", "Borga",
    "Borka", "Borzha", "Brugha", "Bruzka", "Buzga", "Dagra", "Dagrisha",
    "Dashka", "Dragna", "Draka", "Drogma", "Drubish", "Dugha", "Dugra",
    "Durgha", "Durgola", "Durgra", "Durza", "Dushka", "Dushra", "Fangra",
    "Fargha", "Garza", "Gasha", "Gashnish", "Gashra", "Gazma", "Ghasha",
    "Ghashka", "Ghorba", "Glarza", "Globa", "Gludra", "Gnarla", "Gorlish",
    "Gorza", "Gorzha", "Gorzula", "Gozba", "Grakka", "Grasha", "Grashka",
    "Grimba", "Grimzish", "Groba", "Grobna", "Grodha", "Grolka", "Gromsha",
    "Grubna", "Gruzka", "Guldish", "Gulka", "Gulra", "Hagga", "Hakra", "Hazbra",
    "Horga", "Hrulga", "Hurza", "Hurzish", "Kagra", "Kagrisha", "Karga",
    "Karsha", "Karzha", "Kazga", "Khrosha", "Krashnish", "Krogga", "Krugha",
    "Krugna", "Kruzha", "Kuldra", "Kulgra", "Lagdra", "Lagra", "Lagrisha",
    "Lugbish", "Lugha", "Lugna", "Lurgisha", "Lurka", "Magra", "Magrisha",
    "Maugra", "Mauzga", "Mogdish", "Mogra", "Mogratha", "Morza", "Mugdra",
    "Mugra", "Murza", "Muzdra", "Muzga", "Nagra", "Nagruba", "Narba", "Nargha",
    "Narsha", "Narzish", "Nazga", "Nuzga", "Ogdra", "Oggra", "Oghra", "Ogra",
    "Olgdra", "Olgrish", "Orba", "Orgra", "Orzha", "Prugha", "Pugra", "Ragha",
    "Ragra", "Rakka", "Ratka", "Rugba", "Rugda", "Ruzdra", "Ruzga", "Ruzgish",
    "Shagbura", "Shagdish", "Shagra", "Shagrisha", "Shakha", "Shazka", "Shazra",
    "Shrakka", "Shuzga", "Skagra", "Skarna", "Skorga", "Skragga", "Snagga",
    "Snagra", "Snarlish", "Snurga", "Thakra", "Thragga", "Thraka", "Throgga",
    "Thrugba", "Thrugga", "Thurza", "Tugra", "Tugrish", "Tuzga", "Ubra",
    "Ugbisha", "Ugdish", "Ughla", "Ugra", "Ugrisha", "Ukdra", "Ukra", "Ulgra",
    "Ulgrisha", "Ulka", "Urba", "Urgha", "Urgish", "Uzga", "Uzgra", "Varga",
    "Vargha", "Vorgra", "Vorsha", "Vugra", "Vurka", "Yagbish", "Yagda", "Yagra",
    "Yazgra", "Yazha", "Zagba", "Zagra", "Zogra", "Zogrisha", "Zugra", "Zurga",
    "Zurgisha",
]
export const MORDOR_NAMES: NamesByGender = {
    male: MORDOR_MALE_NAMES,
    female: MORDOR_FEMALE_NAMES,
    neutral: [...MORDOR_MALE_NAMES, ...MORDOR_FEMALE_NAMES],
}
