import type { NamesByGender } from "src/constants/markovNamePresets"

const NORSE_MALE_NAMES = [
    "Agnar", "Aki", "Alf", "Alfgeir", "Alrik", "Ambjorn", "Anund", "Arnbjorn",
    "Arne", "Arnfinn", "Arngrim", "Arnkel", "Arnljot", "Asbjorn", "Asger",
    "Askel", "Aslak", "Asmund", "Atli", "Audun", "Bard", "Bersi", "Birger",
    "Bjarke", "Bjarni", "Bjorn", "Bodolf", "Bodvar", "Bolli", "Bolverk",
    "Borkur", "Bragi", "Brand", "Brodir", "Brusi", "Dag", "Dagfinn", "Dyre",
    "Egil", "Eilif", "Einar", "Eindride", "Eirik", "Eldgrim", "Erlend",
    "Erling", "Eyolf", "Eystein", "Eyvind", "Finn", "Finnbogi", "Floki",
    "Fridleif", "Frode", "Gardar", "Gaut", "Geir", "Gisli", "Gizur", "Glum",
    "Gorm", "Grettir", "Grim", "Gudbrand", "Gudmund", "Gunnar", "Gunnlaug",
    "Guttorm", "Hafgrim", "Hakon", "Halfdan", "Hallbjorn", "Hallfred",
    "Hallgrim", "Hallkel", "Hallstein", "Hallvard", "Halvard", "Hamund",
    "Harald", "Hastein", "Hauk", "Helgi", "Heming", "Herjolf", "Hjalmar",
    "Hjalti", "Hogni", "Holmgeir", "Hord", "Hoskuld", "Hrafn", "Hrafnkel",
    "Hrani", "Hreidar", "Hrolf", "Hrut", "Illugi", "Ingimund", "Ingolf",
    "Ingvar", "Isleif", "Ivar", "Jarl", "Jokul", "Jostein", "Kaare", "Kalf",
    "Kari", "Karl", "Ketil", "Ketilbjorn", "Kjartan", "Knut", "Kodran",
    "Kolbein", "Kolbjorn", "Kolskegg", "Leif", "Lodin", "Magnus", "Mord",
    "Njal", "Odd", "Oddleif", "Ogmund", "Olaf", "Olvir", "Onund", "Orlyg",
    "Orm", "Ospak", "Ottar", "Ozur", "Ragnar", "Ragnvald", "Randver",
    "Rognvald", "Rolf", "Runolf", "Saemund", "Sighvat", "Sigmund", "Sigtrygg",
    "Sigurd", "Sigvald", "Skafti", "Skarde", "Skeggi", "Skuli", "Snorri",
    "Solvi", "Sorli", "Starkad", "Steinar", "Steinthor", "Sten", "Sturla",
    "Styrbjorn", "Sumarlidi", "Svein", "Sveinbjorn", "Sven", "Thangbrand",
    "Thidrek", "Thjodolf", "Thorarin", "Thorbjorn", "Thord", "Thorfinn",
    "Thorgeir", "Thorgrim", "Thorir", "Thorkel", "Thorleif", "Thormod",
    "Thorodd", "Thorolf", "Thorstein", "Thorvald", "Thorvard", "Tofi", "Toke",
    "Torstein", "Tostig", "Trygve", "Ulf", "Ulfar", "Ulfljot", "Uni", "Vagn",
    "Valgard", "Valthjof", "Vermund", "Vestein", "Vidar", "Vigfus", "Vigi",
    "Yngvar", "Yngve",
]
const NORSE_FEMALE_NAMES = [
    "Aesa", "Aldis", "Alfdis", "Alfhild", "Alfrun", "Alof", "Arnbjorg",
    "Arndis", "Arngunn", "Arnhild", "Asa", "Asbjorg", "Asdis", "Ase", "Asfrid",
    "Asgerd", "Asgunn", "Aslaug", "Aslog", "Asta", "Astrid", "Asvor", "Aud",
    "Auda", "Bera", "Bergdis", "Bergljot", "Bergthora", "Birna", "Bjorg",
    "Bodil", "Borghild", "Borgny", "Bothild", "Brynhild", "Brynja", "Dagmar",
    "Dagny", "Dagrun", "Dalla", "Dis", "Droplaug", "Eir", "Eldrid", "Embla",
    "Estrid", "Eydis", "Eyja", "Eyvor", "Freya", "Freydis", "Frida", "Fridgerd",
    "Geirhild", "Geirny", "Gerd", "Gjaflaug", "Gjertrud", "Grelod", "Grima",
    "Gro", "Groa", "Gudbjorg", "Gudlaug", "Gudny", "Gudrid", "Gudrun",
    "Gudveig", "Gunhild", "Gunnbjorg", "Gunnhild", "Gunnvor", "Gyda", "Gyrid",
    "Halla", "Hallbera", "Halldis", "Hallfrid", "Hallgerd", "Hallkatla",
    "Hallny", "Hallveig", "Heid", "Hekla", "Helga", "Helgunn", "Herborg",
    "Herdis", "Hervor", "Hild", "Hilda", "Hildigerd", "Hildigunn", "Hildur",
    "Hjordis", "Hlif", "Hrafnhild", "Hrefna", "Idun", "Inga", "Ingeborg",
    "Ingeleif", "Ingibjorg", "Ingirid", "Ingrid", "Ingunn", "Ingveld", "Jodis",
    "Jofrid", "Jora", "Jorunn", "Kara", "Katla", "Ketilrid", "Kolfinna",
    "Kolgrima", "Lif", "Liv", "Ljot", "Ljotunn", "Ljufa", "Magnhild",
    "Nidbjorg", "Oddbjorg", "Oddny", "Oddrun", "Olof", "Osk", "Ragna",
    "Ragnborg", "Ragnfrid", "Ragnheid", "Ragnhild", "Ragnvei", "Ragnvor",
    "Rannveig", "Runa", "Saga", "Salbjorg", "Sif", "Sigbjorg", "Sigdis",
    "Sigfrid", "Sighild", "Signe", "Signy", "Sigrdrifa", "Sigrid", "Sigrun",
    "Sigyn", "Skjalddis", "Solgerd", "Solrun", "Solveig", "Steinunn",
    "Steinvor", "Sunniva", "Svala", "Svanhild", "Svanhvit", "Svanlaug",
    "Thjodhild", "Thora", "Thorbjorg", "Thordis", "Thorey", "Thorfinna",
    "Thorgerd", "Thorgunna", "Thorhild", "Thorkatla", "Thorlaug", "Thorny",
    "Thorunn", "Thorvor", "Thurid", "Thyra", "Tofa", "Tora", "Tordis", "Torunn",
    "Tove", "Turid", "Ulfheid", "Ulfhild", "Ulfrun", "Una", "Unn", "Unnur",
    "Vala", "Valborg", "Valdis", "Valgerd", "Vedis", "Vigdis", "Vilborg",
    "Ylva", "Yngvi", "Yngvild", "Yrsa",
]
export const NORSE_NAMES: NamesByGender = {
    male: NORSE_MALE_NAMES,
    female: NORSE_FEMALE_NAMES,
    neutral: [...NORSE_MALE_NAMES, ...NORSE_FEMALE_NAMES],
}
