export const SPANISH_WORDS = [
    "abanderado", "abanico", "abeja", "abismo", "abrazo", "abrigo",
    "abuelo", "acantilado", "aceite", "aceituna", "acequia", "acero",
    "acertijo", "acuarela", "acuerdo", "adivino", "adobe", "adquirir",
    "agua", "aguacate", "agudos", "aguila", "aguja", "ahijado", "alabastro",
    "alacena", "alambre", "alameda", "alba", "albahaca", "albergue",
    "alcachofa", "alcazar", "alcoba", "aldea", "alegoria", "alegre",
    "alegria", "alfarero", "alfombra", "algodon", "aljibe", "alma",
    "almena", "almendra", "almohada", "alondra", "alpaca", "altamar",
    "altar", "altura", "amanecer", "amapola", "amatista", "ambar", "amigo",
    "amor", "amuleto", "anciano", "ancla", "andamio", "anillo", "animal",
    "anochecer", "antifaz", "antiheroes", "antorcha", "anzuelo", "añorador",
    "aparejo", "apellido", "arado", "araña", "arbol", "arboleda", "arcilla",
    "arcoiris", "ardilla", "arena", "armadura", "armario", "arpa",
    "arquero", "arrecife", "arroyo", "arroz", "arrullo", "artesano",
    "asombro", "astilla", "astronauta", "atalaya", "atardecer", "aurora",
    "avellana", "avellano", "avena", "aventura", "avestruz", "azafran",
    "azahar", "azotea", "azucar", "azucena", "azulejo", "bahia", "bailarin",
    "balcon", "ballena", "baluarte", "bambu", "bandera", "banquete",
    "barco", "barquero", "barranco", "barril", "bastion", "baston",
    "batalla", "baul", "belleza", "bellota", "berenjena", "bergantin",
    "biblioteca", "bigote", "bizcocho", "blancura", "bodega", "bombilla",
    "bonanza", "bordado", "borrasca", "bosque", "botella", "boveda",
    "brasero", "brisa", "brocado", "brujula", "bruma", "bufanda", "buho",
    "burbuja", "burro", "buzon", "cabalgata", "caballo", "cabaña", "cabeza",
    "cabra", "cacao", "cactus", "cadena", "cadera", "cafetera", "calabaza",
    "caldero", "calendario", "calesa", "caliz", "caliza", "calle",
    "camello", "caminante", "camino", "camisa", "campana", "campanario",
    "campesino", "canasta", "cancion", "candado", "candela", "candil",
    "canela", "cangrejo", "canoa", "cantando", "cantaro", "cantera",
    "cantimplora", "capilla", "capitan", "caracol", "caramelo", "caravana",
    "carbon", "cardenal", "cariño", "carruaje", "cartografo", "cascabel",
    "cascada", "castaña", "castillo", "catedral", "cazador", "cebolla",
    "cencerro", "cenizas", "centinela", "cepillo", "cereza", "cerezo",
    "cerradura", "cerrojo", "chimenea", "chocolate", "cielo", "cigarra",
    "cigueña", "cima", "cisne", "ciudad", "claridad", "clavel", "cloro",
    "cobre", "cocina", "codicioso", "codorniz", "cofre", "cohetes", "cojin",
    "colaboracion", "colina", "colonia", "cometa", "cometido", "compas",
    "complejo", "comunion", "concha", "conejo", "confianza", "configurado",
    "conserjes", "contabilidad", "continuando", "contrapaso",
    "coordinacion", "corazon", "corcho", "cordero", "cordillera",
    "coreografiado", "corona", "correccion", "correspondencia", "cosecha",
    "costa", "crecimientos", "crepusculo", "crioscopia", "criptologias",
    "cristal", "cristos", "cromoforo", "cronometros", "crudeza", "crudo",
    "cuaderno", "cuadruples", "cuchara", "cuento", "cuervo", "cueva",
    "cumbre", "cuna", "curvatura", "dadiva", "daga", "dalia", "dama",
    "danza", "dardo", "decodificacion", "dedo", "deflexiones", "dehesa",
    "delantal", "delfin", "delta", "demonizado", "depreciando", "derivas",
    "desahuciado", "desaparecidos", "desconocimiento", "deseo",
    "desertores", "desfavorable", "desfiladero", "desheredados",
    "deshonestidad", "desierto", "desiertos", "despiadado", "despido",
    "despidos", "destello", "destilacion", "destino", "desvan", "devocion",
    "diadema", "diamante", "dibujo", "dicha", "dientes", "difusa",
    "diluvio", "dintel", "diosa", "discrecionalmente", "disfraz",
    "disminucion", "disputable", "distancia", "disuasion", "divaricacion",
    "divulga", "doblon", "domingo", "donaire", "doncella", "dorado",
    "dragon", "dramatico", "ducado", "duelo", "duende", "dulce", "dulzura",
    "duna", "durazno", "ebano", "eclipse", "eco", "economica",
    "economizacion", "edad", "edificio", "ejercito", "electronica",
    "elefante", "elevacion", "elixir", "embellecedores", "embrujo",
    "emigrados", "eminencias", "emperador", "encaje", "encanto", "encina",
    "encrucijada", "enebro", "enfermo", "engañoso", "enigma", "enjuague",
    "enredadera", "ensenada", "ensueño", "entero", "entrada", "epigonismos",
    "epopeya", "equipaje", "equivalente", "erizo", "ermita", "escalera",
    "escarabajo", "escarcha", "escoba", "escorpion", "escritorios",
    "escudo", "esculpida", "escultor", "esencia", "esfinge", "esmeralda",
    "espada", "españa", "espejo", "esperanza", "espiga", "espina",
    "espiritu", "espliego", "espuma", "establo", "estadistica",
    "estandarte", "estanque", "estatua", "estela", "estepa",
    "estereotipadas", "estimulacion", "estio", "estrecho", "estrella",
    "estribo", "estuario", "estuco", "eternidad", "euforia", "evitable",
    "exactamente", "exclama", "excursion", "exhumacion", "expectantes",
    "extorsionador", "fabula", "faena", "fantasma", "farmaceuticas", "faro",
    "farol", "fases", "felino", "feminismos", "fenilalaninas", "fenolico",
    "feria", "ferrimagnetismos", "fiesta", "financieramente", "fino",
    "fiscalistas", "flecha", "flexion", "flor", "fortaleza", "forzada",
    "fosiles", "fracciones", "fragua", "franquicias", "frecuentes",
    "fresno", "frio", "frontera", "frustracion", "fruta", "fuego", "fuente",
    "fuerzas", "fulgor", "funcionarios", "gacela", "gaita", "galeon",
    "galleta", "gallina", "gallo", "ganso", "garza", "gato", "gaviota",
    "gemela", "gemido", "gente", "geranio", "gigante", "girasol", "glaciar",
    "globo", "golondrina", "gorrion", "granada", "granero", "granizo",
    "grillo", "grulla", "gruta", "guante", "guardian", "guijarro", "guinda",
    "guitarra", "hacienda", "hada", "halcon", "harina", "hebilla",
    "hechizo", "helada", "helecho", "herbario", "hermano", "herrero",
    "hidromel", "hiedra", "hielo", "hierba", "higuera", "hilo", "hoguera",
    "hoja", "hongo", "horizonte", "hormiga", "hormiguero", "huella",
    "huerta", "huerto", "hueso", "idilio", "iglesia", "ilusion", "imagen",
    "iman", "imperio", "impopularidades", "imputables", "inadvertencia",
    "incendio", "incienso", "incisivos", "incrustados", "indefensos",
    "indefinidamente", "indigo", "infancia", "infinito", "inflamadores",
    "infrautilizacion", "ingenio", "inquilino", "insecto", "insignia",
    "inspiracion", "instante", "inteligente", "intercalando",
    "intercambiador", "interceptadores", "interconexion", "interesante",
    "intracardio", "intriga", "invernadero", "invierno", "invitado", "iris",
    "irresponsable", "isla", "isleño", "isleta", "istmo", "jabali", "jabon",
    "jardin", "jazmin", "jilguero", "jinete", "jirafa", "joya", "juego",
    "junco", "ladera", "ladrillo", "lagarto", "lago", "lagrima", "laguna",
    "lanza", "latido", "laurel", "lavanda", "lechuza", "leña", "leñador",
    "leon", "libelula", "libro", "lienzo", "lima", "limon", "lino", "lirio",
    "llama", "llanura", "llave", "lluvia", "lobo", "locura", "loro",
    "lucero", "luciernaga", "luna", "madera", "madreselva", "madrugada",
    "magnetosferico", "maiz", "majestad", "malestar", "malva", "manantial",
    "mandarina", "manta", "mantel", "manufacturas", "manzana", "mañana",
    "marea", "marfil", "marinero", "mariposa", "marisma", "marmol",
    "martillo", "mas", "mascaras", "mascota", "mastil", "materialismos",
    "mayor", "mayoritarismo", "mazmorra", "mecedora", "medianoche",
    "medicamentos", "megavitaminas", "mejillon", "melocoton", "melodia",
    "membrillo", "memorializada", "menta", "meperidinas", "mercado",
    "meseta", "metros", "mia", "microinjertos", "microtonalidad", "miel",
    "milagro", "mimbre", "mirada", "mirador", "mirlo", "mismo",
    "misticamente", "mochila", "molestias", "molino", "moneda", "monje",
    "montaña", "morada", "muñeca", "muricado", "murmullo", "musgo", "nacar",
    "naranja", "nardo", "naturaleza", "navaja", "nenufar", "nido", "niebla",
    "nieve", "nivel", "noche", "nocturna", "nogal", "nostalgia", "novios",
    "nube", "nudo", "nutria", "oasis", "obsidiana", "ocaso", "ofensiva",
    "ola", "oleaje", "olivo", "olores", "olvido", "oreja", "orgulloso",
    "orilla", "oro", "oruga", "oso", "ostra", "otoño", "oveja", "pabellon",
    "pacificar", "paisaje", "paisanos", "pajar", "pajaro", "palabra",
    "palacio", "palillo", "palmera", "paloma", "pan", "panal", "pantano",
    "pantera", "papel", "paraguas", "paramo", "parra", "pasillo",
    "pasividad", "pastor", "patente", "paulatina", "pavo", "peldaño",
    "pelicano", "pellejo", "pepino", "peregrinacion", "peregrino", "perla",
    "permeabilidad", "perpetuacion", "perro", "persuadir", "pescador",
    "petalo", "pez", "picante", "piedra", "pimienta", "pinar", "pino",
    "pinzon", "pirata", "pisoteado", "pizarra", "plagas", "plagio",
    "planimetro", "planos", "plaqueta", "plata", "platano", "playa",
    "plaza", "pliegues", "pluma", "poema", "polimerizacion", "politeismo",
    "pontificador", "portada", "posesivo", "pozo", "pradera", "prado",
    "preadoptados", "preconscientes", "predicacion", "prediccion",
    "prefecturas", "preprogramacion", "prerrequisitos", "primavera",
    "procuradores", "profetizado", "pronostico", "prueba", "pueblo",
    "puente", "puerta", "pulpo", "puntuales", "puntualmente", "quebrada",
    "queso", "quietud", "quijote", "quimera", "quinta", "racimo", "rama",
    "ramo", "rampa", "rana", "ranurado", "rareza", "rayo", "reanimacion",
    "rebaño", "recodo", "rectora", "recuerdo", "redefinicion", "redoble",
    "reeleccion", "reflexion", "reformatorios", "reformulado", "refugio",
    "regalo", "regulador", "reina", "reingreso", "relampago", "religiosos",
    "reloj", "remo", "renacimiento", "renuncia", "represalias", "reproche",
    "resina", "respaldo", "retama", "retenciones", "retrospectivamente",
    "revestimiento", "revocacion", "riachuelo", "ribera", "rincon", "rio",
    "risco", "ritualistas", "roble", "rocio", "ronda", "rosa", "rubi",
    "rudo", "rueda", "ruiseñor", "rumbo", "rupturas", "sabana", "sabio",
    "sabor", "salamandra", "salina", "salmon", "salto", "salvaje", "salvia",
    "sandalia", "sandia", "sangre", "santuario", "sardina", "saturnismo",
    "sauce", "sauces", "sauco", "secreto", "seis", "selva", "semana",
    "semblanza", "semilla", "senda", "sendero", "sepia", "serenata",
    "sereno", "serpiente", "servicios", "sierra", "significado", "silencio",
    "silueta", "sintonizado", "sirena", "sobre", "sobrecarga", "sol",
    "solitario", "sombra", "sombrero", "sonido", "sonrisa", "soplado",
    "soplador", "sorprendentemente", "sortija", "sotano", "subcontratacion",
    "subitos", "sueño", "superavit", "susurro", "taberna", "tabla",
    "taller", "tambor", "tapiz", "tarde", "taza", "tejado", "tejer",
    "tejon", "telaraña", "telefoto", "tempestad", "templo", "teologia",
    "terciopelo", "terraza", "tesoro", "tetracloruros", "tiburon", "tiempo",
    "tierno", "tierra", "tigre", "tijera", "tijeras", "timon", "tinaja",
    "tintero", "tintes", "tomillo", "topacio", "tormenta", "torre",
    "torrente", "tortuga", "tos", "tranquilizado", "transductores",
    "transgresora", "trascendental", "travesia", "trigo", "trineo",
    "trompeta", "trovador", "trueno", "tulipan", "tunel", "turbante",
    "turismo", "ultramar", "ultramodernistas", "umbral", "urbanologos",
    "urraca", "utilitarismo", "uva", "vacante", "vagabundo", "valentias",
    "valija", "valle", "vaso", "vela", "veloz", "venado", "vendaval",
    "ventana", "verano", "verdaderamente", "vereda", "vertiginoso",
    "vestir", "viajero", "vicios", "vid", "vidrio", "viento", "viñedo",
    "violeta", "violin", "vispera", "vocales", "volcan", "xenolitos",
    "yedra", "yegua", "yelmo", "yunque", "zafiro", "zanahoria", "zapato",
    "zarza", "zorro", "zorzal", "zumo",
]
