export const SPANISH_WORDS = [
    "abeja", "abrazo", "abuelo", "agua", "aguila", "alegria", "alma",
    "almendra", "amanecer", "amigo", "amor", "arbol", "arena", "arroyo",
    "azucar", "bahia", "ballena", "bandera", "barco", "belleza", "bosque",
    "brisa", "burbuja", "caballo", "cabeza", "cadena", "calle", "camino",
    "campana", "cancion", "caracol", "cariño", "castillo", "cebolla",
    "cereza", "cielo", "ciudad", "colina", "corazon", "cordero", "cuchara",
    "cuento", "cueva", "dedo", "delfin", "desierto", "destino", "diamante",
    "dulce", "espejo", "espada", "espiritu", "estrella", "fantasma",
    "fiesta", "flecha", "flor", "fortaleza", "fuego", "fuente", "galleta",
    "gato", "gigante", "girasol", "golondrina", "guitarra", "hermano",
    "hielo", "hierba", "hoguera", "hormiga", "horizonte", "huella", "huerto",
    "iglesia", "invierno", "isla", "jardin", "jazmin", "joya", "juego",
    "lagrima", "lagarto", "laguna", "leche", "lechuza", "leña", "leon",
    "libro", "limon", "llama", "llave", "lluvia", "lobo", "locura", "luna",
    "madera", "madrugada", "mañana", "manzana", "mariposa", "martillo",
    "melodia", "mercado", "miel", "milagro", "mirada", "molino", "montaña",
    "muñeca", "naranja", "naturaleza", "navaja", "niebla", "nieve", "noche",
    "nube", "olivo", "ola", "oreja", "oro", "otoño", "paloma", "pajaro",
    "palabra", "pan", "pantano", "paraguas", "pasillo", "pellejo", "pepino",
    "perro", "piedra", "pimienta", "pino", "playa", "pluma", "poema",
    "primavera", "pueblo", "puente", "puerta", "queso", "quimera", "rana",
    "rayo", "recuerdo", "refugio", "reina", "relampago", "reloj", "rio",
    "roble", "rocio", "rosa", "rueda", "sabana", "sabor", "salvaje",
    "sandia", "sangre", "selva", "semilla", "sendero", "serpiente",
    "silencio", "sirena", "sol", "sombra", "sonrisa", "sueño", "tambor",
    "tarde", "tejado", "tesoro", "tiburon", "tiempo", "tierra", "tigre",
    "tormenta", "tortuga", "trueno", "tulipan", "urraca", "uva", "valle",
    "vaso", "vela", "ventana", "verano", "viento", "volcan", "yegua",
    "zapato", "zorro", "zumo", "cantaro", "hechizo", "lucero", "marea",
]
