import { PresetGroup } from "src/components/PresetsPanel"

type NamesByGender = {
    male: string[]
    female: string[]
    neutral: string[]
}

function buildStylePresetGroup(
    styleLabel: string,
    { male, female, neutral }: NamesByGender,
): PresetGroup<string[]> {
    return {
        label: styleLabel,
        presets: [
            { label: "Male", value: male },
            { label: "Female", value: female },
            { label: "Neutral", value: neutral },
        ],
    }
}

const JAPANESE_NAMES: NamesByGender = {
    male: [
        "Akihiro", "Akio", "Arata", "Atsushi", "Daichi", "Daiki", "Daisuke",
        "Eiji", "Fumio", "Goro", "Hajime", "Haruki", "Haruto", "Hayato",
        "Hideaki", "Hideki", "Hideo", "Hiroki", "Hiroshi", "Hiroto",
        "Hisashi", "Ichiro", "Isamu", "Isao", "Jiro", "Junichi", "Kaito",
        "Kanta", "Katsuo", "Katsuro", "Kazuki", "Kazuo", "Kazuya", "Keiichi",
        "Keisuke", "Kenichi", "Kenji", "Kenta", "Kentaro", "Kiyoshi",
        "Koichi", "Koji", "Kosuke", "Kota", "Kotaro", "Mamoru", "Manabu",
        "Masahiro", "Masao", "Masaru", "Masato", "Masayuki", "Michio",
        "Minato", "Minoru", "Mitsuo", "Naoto", "Nobuo", "Nobuyuki", "Noboru",
        "Norio", "Osamu", "Renji", "Riku", "Ryohei", "Ryosuke", "Ryota",
        "Ryuji", "Ryunosuke", "Saburo", "Satoru", "Satoshi", "Seiji",
        "Shigeru", "Shinji", "Shinya", "Shiro", "Shota", "Shunsuke", "Sosuke",
        "Souta", "Susumu", "Tadashi", "Taichi", "Taiga", "Takahiro",
        "Takashi", "Takeshi", "Takumi", "Takuya", "Taro", "Tatsuya",
        "Tetsuya", "Toru", "Toshiro", "Tsuyoshi", "Yamato", "Yasuo",
        "Yosuke", "Yusuke",
    ],
    female: [
        "Aiko", "Akane", "Akemi", "Ami", "Asami", "Asuka", "Atsuko", "Ayaka",
        "Ayako", "Ayame", "Ayano", "Chiaki", "Chie", "Chieko", "Chiharu",
        "Chiyo", "Chiyoko", "Emi", "Emiko", "Eri", "Etsuko", "Fumiko",
        "Hanae", "Hanako", "Haruka", "Haruna", "Hina", "Hinako", "Hisako",
        "Hitomi", "Honoka", "Hotaru", "Junko", "Kana", "Kanako", "Kanon",
        "Kaori", "Kasumi", "Kayo", "Kazuko", "Keiko", "Kimiko", "Kiyoko",
        "Kotone", "Kumiko", "Kyoko", "Mai", "Maiko", "Mami", "Mana",
        "Manami", "Mariko", "Masako", "Mayu", "Mayumi", "Megumi", "Mei",
        "Michiko", "Midori", "Mie", "Miho", "Mika", "Miki", "Mina", "Minako",
        "Misaki", "Mitsuko", "Miyu", "Miyuki", "Momoka", "Momoko", "Nana",
        "Nanami", "Naoko", "Natsumi", "Noriko", "Nozomi", "Reiko", "Rie",
        "Rika", "Rina", "Risa", "Ryoko", "Sachiko", "Saki", "Sakura",
        "Sanae", "Sayaka", "Sayuri", "Setsuko", "Shiori", "Shizuka",
        "Sumiko", "Tomoe", "Tomoko", "Yoko", "Yoshiko", "Yui", "Yumiko",
        "Yuriko",
    ],
    neutral: [
        "Aki", "Akira", "Aoi", "Asahi", "Ayumu", "Chihiro", "Haru", "Haruhi",
        "Harumi", "Hibiki", "Hikari", "Hikaru", "Hinata", "Hiromi", "Hisami",
        "Ibuki", "Iori", "Itsuki", "Izumi", "Jun", "Kaede", "Kanade",
        "Kaname", "Kaoru", "Kazu", "Kazumi", "Kei", "Kiyomi", "Kohaku", "Kou",
        "Kyo", "Mahiro", "Makoto", "Masami", "Masumi", "Michi", "Mikoto",
        "Minori", "Mirai", "Mitsuki", "Mizuki", "Nagisa", "Nanase", "Nao",
        "Naomi", "Natsu", "Natsuki", "Nozomu", "Rei", "Ren", "Rin", "Rui",
        "Ruka", "Ryo", "Sachi", "Sakae", "Satomi", "Sei", "Shiki", "Shinobu",
        "Shion", "Shizuku", "Sora", "Sou", "Subaru", "Tadami", "Takami",
        "Tamaki", "Tatsumi", "Tomo", "Tomomi", "Toshimi", "Tsubasa",
        "Tsukasa", "Umi", "Yoshimi", "Yu", "Yuu", "Yuki", "Yukimi", "Yuuki",
        "Yuzu", "Yuzuki", "Akari", "Chiaya", "Fuyu", "Hayase", "Hotaka",
        "Kagari", "Kanata", "Kiri", "Kotori", "Mao", "Mihiro", "Nagi",
        "Hijiri", "Rio", "Sena", "Tsubaki", "Yuma",
    ],
}

const ENGLISH_NAMES: NamesByGender = {
    male: [
        "Aaron", "Adam", "Albert", "Alfred", "Andrew", "Anthony", "Arthur",
        "Barnaby", "Benedict", "Benjamin", "Bernard", "Bertram", "Cecil",
        "Charles", "Christopher", "Clarence", "Clement", "Clifford", "Colin",
        "Cuthbert", "Cyril", "David", "Dennis", "Derek", "Desmond", "Douglas",
        "Duncan", "Edgar", "Edmund", "Edward", "Edwin", "Ernest", "Eugene",
        "Felix", "Francis", "Frederick", "Gareth", "Geoffrey", "George",
        "Gerald", "Gilbert", "Gordon", "Graham", "Gregory", "Harold",
        "Herbert", "Horace", "Howard", "Hubert", "Hugh", "Humphrey", "Ian",
        "Jack", "James", "Jasper", "Jeremy", "John", "Jonathan", "Joseph",
        "Julian", "Kenneth", "Laurence", "Leonard", "Lewis", "Malcolm",
        "Martin", "Matthew", "Maurice", "Michael", "Nathaniel", "Neville",
        "Nicholas", "Nigel", "Norman", "Oliver", "Oscar", "Oswald", "Patrick",
        "Percival", "Peter", "Philip", "Ralph", "Raymond", "Reginald",
        "Richard", "Robert", "Roger", "Ronald", "Rupert", "Samuel",
        "Sebastian", "Simon", "Stanley", "Stephen", "Theodore", "Thomas",
        "Timothy", "Tobias", "Walter", "William",
    ],
    female: [
        "Abigail", "Ada", "Adelaide", "Agatha", "Agnes", "Alice", "Amelia",
        "Anne", "Annabel", "Audrey", "Beatrice", "Bella", "Bridget",
        "Caroline", "Catherine", "Cecily", "Charlotte", "Clara", "Constance",
        "Cordelia", "Daisy", "Diana", "Dorothy", "Edith", "Eleanor", "Eliza",
        "Elizabeth", "Ella", "Eloise", "Emily", "Emma", "Esther", "Ethel",
        "Evelyn", "Felicity", "Fiona", "Florence", "Frances", "Georgina",
        "Gertrude", "Grace", "Gwendolyn", "Hannah", "Harriet", "Hazel",
        "Helen", "Henrietta", "Imogen", "Iris", "Isabel", "Ivy", "Jane",
        "Janet", "Josephine", "Joyce", "Judith", "Julia", "Juliet",
        "Katherine", "Laura", "Lillian", "Louisa", "Lucy", "Lydia", "Mabel",
        "Margaret", "Marian", "Martha", "Mary", "Matilda", "Maud", "Mildred",
        "Miranda", "Molly", "Muriel", "Nancy", "Olive", "Olivia", "Penelope",
        "Philippa", "Phoebe", "Priscilla", "Rachel", "Rebecca", "Rosalind",
        "Rose", "Ruth", "Sarah", "Sophia", "Susanna", "Sylvia", "Theodora",
        "Ursula", "Victoria", "Violet", "Wendy", "Winifred", "Mavis",
        "Beryl", "Doris",
    ],
    neutral: [
        "Addison", "Ainsley", "Alex", "Alexis", "Arden", "Ari", "Ash",
        "Aubrey", "August", "Avery", "Bailey", "Blair", "Blake", "Brook",
        "Cameron", "Carson", "Casey", "Charlie", "Chris", "Dakota", "Dale",
        "Dallas", "Dana", "Darcy", "Devon", "Drew", "Dylan", "Eden", "Elliot",
        "Ellis", "Emerson", "Emery", "Finley", "Frankie", "Gale", "Gray",
        "Hadley", "Harley", "Harper", "Hayden", "Hollis", "Hunter", "Indigo",
        "Jaden", "Jamie", "Jesse", "Jody", "Jordan", "Jules", "Justice",
        "Kai", "Kelly", "Kendall", "Kennedy", "Kerry", "Kit", "Lane", "Lee",
        "Leslie", "Lindsay", "Logan", "London", "Mackenzie", "Marley",
        "Max", "Micah", "Morgan", "Nico", "Noel", "Oakley", "Parker",
        "Perry", "Peyton", "Phoenix", "Quinn", "Reagan", "Reese", "Remy",
        "Riley", "River", "Robin", "Rory", "Rowan", "Sage", "Sam", "Sasha",
        "Sawyer", "Shannon", "Shay", "Sidney", "Skyler", "Spencer", "Stevie",
        "Sutton", "Tatum", "Taylor", "Teagan", "Terry", "Tracy", "Wren",
    ],
}

const NORSE_MALE_NAMES = [
    "Agnar", "Alf", "Alrik", "Arnbjorn", "Arne", "Asbjorn", "Asger", "Askel",
    "Aslak", "Atli", "Bard", "Bersi", "Birger", "Bjarni", "Bjorn", "Bodvar",
    "Bolli", "Brand", "Brodir", "Dag", "Egil", "Eilif", "Einar", "Eindride",
    "Eirik", "Erlend", "Eyvind", "Finn", "Floki", "Frode", "Geir", "Gisli",
    "Gorm", "Grim", "Gudmund", "Gunnar", "Guttorm", "Hakon", "Halfdan",
    "Hallbjorn", "Hallstein", "Halvard", "Harald", "Hastein", "Hauk",
    "Helgi", "Hjalmar", "Hrafn", "Hrolf", "Ingolf", "Ingvar", "Ivar", "Jarl",
    "Kaare", "Ketil", "Kjartan", "Knut", "Kolbein", "Leif", "Magnus", "Njal",
    "Odd", "Olaf", "Olvir", "Orm", "Ottar", "Ragnar", "Ragnvald", "Randver",
    "Rolf", "Sigmund", "Sigurd", "Sigvald", "Skafti", "Skarde", "Snorri",
    "Solvi", "Steinar", "Sten", "Styrbjorn", "Svein", "Sven", "Thorbjorn",
    "Thorfinn", "Thorgrim", "Thorkel", "Thorleif", "Thorolf", "Thorstein",
    "Thorvald", "Toke", "Torstein", "Trygve", "Ulf", "Ulfar", "Valgard",
    "Vidar", "Vigfus", "Yngvar", "Hallvard",
]
const NORSE_FEMALE_NAMES = [
    "Alfhild", "Arnhild", "Asa", "Asgerd", "Aslaug", "Asta", "Astrid", "Aud",
    "Bera", "Bergljot", "Bodil", "Borghild", "Brynhild", "Brynja", "Dagny",
    "Dagrun", "Dis", "Eir", "Embla", "Estrid", "Eydis", "Eyja", "Freydis",
    "Freya", "Frida", "Gerd", "Grima", "Groa", "Gudny", "Gudrid", "Gudrun",
    "Gunhild", "Gunnvor", "Gyda", "Halldis", "Hallgerd", "Hallveig", "Heid",
    "Helga", "Herdis", "Hervor", "Hilda", "Hildigunn", "Hjordis", "Hlif",
    "Idun", "Inga", "Ingeborg", "Ingrid", "Ingunn", "Jofrid", "Jorunn",
    "Katla", "Kolfinna", "Liv", "Ljot", "Magnhild", "Oddny", "Osk", "Ragna",
    "Ragnfrid", "Ragnhild", "Ragnvor", "Rannveig", "Runa", "Saga", "Sif",
    "Sigfrid", "Signy", "Sigrid", "Sigrun", "Sigyn", "Solrun", "Solveig",
    "Steinunn", "Svala", "Svanhild", "Thora", "Thordis", "Thorgerd",
    "Thorhild", "Thorunn", "Thurid", "Thyra", "Tofa", "Tora", "Tove",
    "Turid", "Ulfhild", "Una", "Unn", "Vala", "Valborg", "Valdis", "Vigdis",
    "Ylva", "Yngvild", "Yrsa", "Aslog", "Hekla",
]
const NORSE_NAMES: NamesByGender = {
    male: NORSE_MALE_NAMES,
    female: NORSE_FEMALE_NAMES,
    neutral: [...NORSE_MALE_NAMES, ...NORSE_FEMALE_NAMES],
}

const LATIN_MALE_NAMES = [
    "Aemilius", "Agrippa", "Albinus", "Antonius", "Appius", "Aquila",
    "Atticus", "Aulus", "Aurelius", "Avitus", "Balbus", "Brutus", "Caelius",
    "Caesar", "Caius", "Calvus", "Camillus", "Cassius", "Cato", "Celsus",
    "Cicero", "Claudius", "Clemens", "Cornelius", "Crassus", "Crispus",
    "Decimus", "Domitius", "Drusus", "Fabius", "Faustus", "Flavius",
    "Florus", "Gaius", "Galba", "Gallus", "Germanicus", "Gnaeus", "Gracchus",
    "Hadrianus", "Horatius", "Julius", "Junius", "Justus", "Laelius",
    "Lentulus", "Lepidus", "Livius", "Longinus", "Lucius", "Lucretius",
    "Magnus", "Mamercus", "Manius", "Marcellus", "Marcus", "Marius",
    "Maximus", "Nero", "Nerva", "Numerius", "Octavius", "Otho", "Ovidius",
    "Paulus", "Petronius", "Pius", "Plinius", "Pompeius", "Porcius",
    "Priscus", "Publius", "Quintus", "Regulus", "Remus", "Rufus", "Sabinus",
    "Scipio", "Secundus", "Septimus", "Sergius", "Servius", "Severus",
    "Sextus", "Silvanus", "Spurius", "Sulla", "Tacitus", "Tertius",
    "Tiberius", "Titus", "Traianus", "Tullius", "Valens", "Valerius", "Varro",
    "Verus", "Vespasianus", "Vibius", "Vitellius",
]
const LATIN_FEMALE_NAMES = [
    "Aelia", "Aemilia", "Agrippina", "Albina", "Antonia", "Aquilia", "Arria",
    "Atia", "Aurelia", "Aurora", "Caecilia", "Caelia", "Calpurnia",
    "Camilla", "Cassia", "Claudia", "Clodia", "Cornelia", "Crispina",
    "Decima", "Domitia", "Drusilla", "Fabia", "Fausta", "Faustina", "Flavia",
    "Fulvia", "Galeria", "Galla", "Gratia", "Helvia", "Horatia", "Hortensia",
    "Hostilia", "Julia", "Junia", "Justina", "Laelia", "Lavinia", "Licinia",
    "Livia", "Lucia", "Lucilla", "Lucretia", "Marcella", "Marcia",
    "Marciana", "Maxima", "Messalina", "Minervina", "Nonia", "Numeria",
    "Octavia", "Paulina", "Petronia", "Placidia", "Plautia", "Pompeia",
    "Popillia", "Porcia", "Prima", "Priscilla", "Quintilla", "Rufina",
    "Sabina", "Salonina", "Scribonia", "Secunda", "Sempronia", "Septima",
    "Sergia", "Servilia", "Severa", "Severina", "Silvia", "Statilia",
    "Sulpicia", "Terentia", "Tertia", "Tertulla", "Tiberia", "Titia",
    "Tullia", "Ulpia", "Urbica", "Valentina", "Valeria", "Verania",
    "Vergilia", "Vespasia", "Vibia", "Vipsania", "Vitellia", "Volumnia",
    "Aemiliana", "Antistia", "Aquilina", "Caesonia", "Cloelia", "Cominia",
]
const LATIN_NAMES: NamesByGender = {
    male: LATIN_MALE_NAMES,
    female: LATIN_FEMALE_NAMES,
    neutral: [...LATIN_MALE_NAMES, ...LATIN_FEMALE_NAMES],
}

const GREEK_MALE_NAMES = [
    "Achilles", "Adrastos", "Agamemnon", "Alexandros", "Alkaios",
    "Anatolios", "Andreas", "Antonios", "Aristarchos", "Aristides",
    "Aristoteles", "Athanasios", "Charalambos", "Christos", "Damianos",
    "Damon", "Demetrios", "Diomedes", "Dionysios", "Emmanouil",
    "Epaminondas", "Euripides", "Evangelos", "Georgios", "Gregorios",
    "Hektor", "Herakles", "Hermes", "Hippokrates", "Iason", "Ilias",
    "Ioannis", "Isidoros", "Kallias", "Kimon", "Kleon", "Konstantinos",
    "Kosmas", "Kostas", "Kyriakos", "Kyros", "Lambros", "Leandros",
    "Leonidas", "Linos", "Loukas", "Lykourgos", "Lysandros", "Markos",
    "Menelaos", "Michalis", "Miltiades", "Nektarios", "Nestor", "Nikandros",
    "Nikias", "Nikolaos", "Nikos", "Odysseus", "Orestes", "Panagiotis",
    "Pantelis", "Pavlos", "Pericles", "Perseus", "Petros", "Philippos",
    "Photios", "Platon", "Polydoros", "Prokopios", "Pyrrhos", "Sokratis",
    "Solon", "Sophokles", "Spyridon", "Stamatis", "Stavros", "Stefanos",
    "Stelios", "Takis", "Telemachos", "Thanos", "Themistokles", "Theodoros",
    "Theseus", "Thrasyvoulos", "Timon", "Timotheos", "Triantafyllos",
    "Vasilios", "Xenophon", "Yannis", "Zacharias", "Zenon", "Aias",
    "Apostolos", "Fotis", "Ektoras", "Sotirios",
]
const GREEK_FEMALE_NAMES = [
    "Aglaia", "Agapi", "Aikaterini", "Alexandra", "Alkmene", "Amalia",
    "Anastasia", "Andromache", "Andromeda", "Angeliki", "Anthoula",
    "Antigone", "Aphrodite", "Ariadne", "Artemis", "Aspasia", "Athena",
    "Calliope", "Chara", "Chloe", "Chrysanthe", "Chrysoula", "Danae",
    "Daphne", "Despina", "Dimitra", "Doris", "Efthymia", "Eirini", "Electra",
    "Eleftheria", "Eleni", "Elpida", "Eudokia", "Eugenia", "Eurydice",
    "Evadne", "Evangelia", "Foteini", "Galateia", "Georgia", "Hera",
    "Hermione", "Hestia", "Hypatia", "Ioanna", "Iphigenia", "Ismene",
    "Kallisto", "Kalypso", "Kassandra", "Katerina", "Kleio", "Konstantina",
    "Kore", "Kyriaki", "Leto", "Lydia", "Lysandra", "Maria", "Marina",
    "Medea", "Melina", "Melissa", "Melpomene", "Merope", "Myrto",
    "Nausicaa", "Nefeli", "Niki", "Olympia", "Ourania", "Panagiota",
    "Pandora", "Paraskevi", "Penelope", "Persephone", "Phaedra", "Phoebe",
    "Polyxena", "Rhea", "Roxani", "Sappho", "Selene", "Sofia", "Stavroula",
    "Stella", "Styliani", "Terpsichore", "Thalia", "Theano", "Theodora",
    "Theodosia", "Thetis", "Vasiliki", "Xanthe", "Xanthippe", "Zenobia",
    "Zoe", "Iris",
]
const GREEK_NAMES: NamesByGender = {
    male: GREEK_MALE_NAMES,
    female: GREEK_FEMALE_NAMES,
    neutral: [...GREEK_MALE_NAMES, ...GREEK_FEMALE_NAMES],
}

const FANTASY_NAMES: NamesByGender = {
    male: [
        "Aeron", "Alaric", "Aldric", "Arannis", "Arkon", "Arvendel",
        "Baelgar", "Balthor", "Barathor", "Belros", "Borin", "Brannoc",
        "Cador", "Caldor", "Cedrik", "Corvin", "Daelor", "Dagrim", "Darion",
        "Delmar", "Dorian", "Dravek", "Drogan", "Eamon", "Eldrin",
        "Eltharion", "Erevan", "Evrard", "Faelar", "Faramond", "Fendrel",
        "Fenrik", "Galadrin", "Garrick", "Gavric", "Gideon", "Gorvath",
        "Grimward", "Haldor", "Halvric", "Harrow", "Idrin", "Ithron", "Jareth",
        "Joren", "Jorvan", "Kaelen", "Kaldris", "Kaspar", "Korrin", "Kovar",
        "Leoric", "Lorcan", "Lucan", "Maelor", "Magnar", "Malric", "Marek",
        "Mordan", "Morvran", "Nareth", "Nerion", "Nevin", "Oberin", "Orinthal",
        "Orrin", "Orvan", "Osric", "Pelleas", "Perrin", "Pyrrus", "Quenril",
        "Radovan", "Ragnor", "Ravos", "Rhodric", "Riordan", "Roderan",
        "Rurik", "Saevar", "Sarvin", "Sevrin", "Taliesin", "Tavian",
        "Thalion", "Tharivol", "Theron", "Tormund", "Uldor", "Ulric", "Uthar",
        "Valdren", "Vaelric", "Vandrel", "Varian", "Wendric", "Wolfric",
        "Xandor", "Yorick", "Zarek",
    ],
    female: [
        "Aelyn", "Aeliana", "Aerith", "Althea", "Amarelle", "Ariwyn",
        "Aurelle", "Belara", "Brielle", "Brisha", "Brynneth", "Caelira",
        "Calanthe", "Celestra", "Ceridwen", "Corisande", "Cyrene", "Daelyra",
        "Dariel", "Delphine", "Eirlys", "Elandra", "Elara", "Elowen",
        "Elyndra", "Eryndel", "Faelwen", "Fayeth", "Fenella", "Fiorella",
        "Galathil", "Galena", "Gwenhael", "Halwyn", "Hesper", "Ilsabet",
        "Ilyana", "Iriel", "Isara", "Isolde", "Ithilwen", "Jalira",
        "Jessamine", "Kaelira", "Katria", "Kiriel", "Lethiel", "Liora",
        "Lirael", "Lunara", "Lysanthe", "Lyssara", "Maelis", "Maerwen",
        "Melisande", "Mirabel", "Mirelda", "Morwen", "Myrelle", "Naelith",
        "Naeris", "Nerissa", "Nessa", "Nimue", "Nymeria", "Olwen", "Ondine",
        "Oriane", "Orlaith", "Perrine", "Quilla", "Rhiannon", "Rowenna",
        "Sabeth", "Saphira", "Sariel", "Selvara", "Seraphel", "Sylvara",
        "Tamaris", "Taria", "Teleri", "Thessaly", "Tindra", "Ulyana",
        "Undine", "Vaelora", "Valeska", "Velessa", "Venya", "Vivienne",
        "Wynna", "Xyliel", "Yllana", "Ynara", "Ysera", "Yseult", "Zaria",
        "Zelaine", "Zephyrine",
    ],
    neutral: [
        "Aelis", "Aeris", "Alder", "Arin", "Arrow", "Ash", "Ashen", "Aspen",
        "Astra", "Aurel", "Auren", "Briar", "Bryn", "Cael", "Caelith", "Ciel",
        "Cinder", "Corin", "Dael", "Dusk", "Echo", "Elin", "Elio",
        "Ember", "Emrys", "Eris", "Fable", "Faer", "Fenn", "Flint", "Galen",
        "Glade", "Hale", "Haven", "Idris", "Indri", "Ione", "Jae", "Jory",
        "Kael", "Kaelan", "Kestrel", "Kiran", "Laken", "Lark", "Lior",
        "Lirien", "Lumen", "Lyr", "Mael", "Maris", "Merrin", "Mistral",
        "Morrow", "Nael", "Neve", "Nevan", "Nim", "Nyx", "Onyx", "Oren",
        "Pell", "Quen", "Quill", "Raine", "Ren", "Reyn", "Rhys",
        "Riven", "Rook", "Rowan", "Rune", "Sable", "Sael", "Saelwyn",
        "Selwyn", "Shae", "Shale", "Sol", "Solace", "Sorin", "Sparrow",
        "Storm", "Sylas", "Tallis", "Tamsin", "Taryn", "Teague", "Thorne",
        "Tiern", "Tirael", "Umber", "Vael", "Vale", "Vesper", "Wren", "Wynn",
        "Yael", "Zale", "Zephyr",
    ],
}

const ELVISH_MALE_NAMES = [
    "Aegnor", "Aelindor", "Aerandir", "Aerion", "Almarion", "Amdir",
    "Amras", "Amrod", "Amroth", "Anardil", "Angrod", "Annael", "Arandur",
    "Aranwe", "Arathil", "Arminas", "Beleg", "Belegorn", "Calaron",
    "Calenhir", "Caranthir", "Celeborn", "Celebrimbor", "Celegorm",
    "Celendir", "Cirdan", "Curufin", "Daeron", "Daerion", "Duilin",
    "Duinhir", "Ecthelion", "Edhelion", "Edrahil", "Egalmoth", "Eldamir",
    "Elerion", "Elladan", "Elrohir", "Elrond", "Elros", "Enel", "Eol",
    "Erestor", "Faelon", "Falathar", "Finarfin", "Fingolfin", "Fingon",
    "Finrod", "Finwe", "Galadhon", "Galdor", "Galion", "Gelmir", "Gildor",
    "Gil-galad", "Gilrandir", "Glorfindel", "Glorion", "Guilin", "Gwindor",
    "Haldamir", "Haldir", "Ingwe", "Ingwion", "Ithildor", "Legolas", "Lenwe",
    "Lindir", "Lindorion", "Lothion", "Mablung", "Maedhros", "Maglor",
    "Mahtan", "Mirdanor", "Nurion", "Olwe", "Orithil", "Orodreth", "Oropher",
    "Orophin", "Rhovandil", "Rumil", "Saeros", "Silmarion", "Tauron",
    "Thingol", "Thranduil", "Tindomion", "Turgon", "Vanyandil", "Voronwe",
    "Aerendir", "Celebrindor", "Faelivrin", "Gwaerion", "Luinor", "Nimrion",
]
const ELVISH_FEMALE_NAMES = [
    "Aelinel", "Aerwen", "Alassiel", "Amarie", "Anaire", "Anariel", "Aranel",
    "Aredhel", "Arwen", "Beliriel", "Calaniel", "Celebrian", "Celebriel",
    "Cirieth", "Earwen", "Elanor", "Elemmire", "Elenril", "Elenwe", "Eliniel",
    "Elwing", "Estelwen", "Findis", "Finduilas", "Galadriel", "Galathiel",
    "Gilwen", "Idhrien", "Idril", "Ilmare", "Ilmariel", "Indis", "Irime",
    "Laerwen", "Lalwen", "Lindariel", "Lothwen", "Luinwen", "Luthien",
    "Maethiel", "Melian", "Mireth", "Miriel", "Mithrellas", "Nellas",
    "Nerdanel", "Nienna", "Nimloth", "Nimrodel", "Nimwen", "Niriel",
    "Orneth", "Rhosiel", "Tauriel", "Taurwen", "Tinuviel", "Uinen",
    "Undomiel", "Vaire", "Vana", "Vanyariel", "Varda", "Wilwarin", "Yaviel",
    "Yavanna", "Aeglosiel", "Alfirin", "Amariel", "Anorwen", "Arphenel",
    "Belethiel", "Brethiliel", "Caladwen", "Celairiel", "Ninglorien",
    "Elaniel", "Elerrina", "Eruwen", "Faelinel", "Gilraeniel", "Glorwen",
    "Heledir", "Ithiliel", "Lomelinde", "Lissuin", "Loriel", "Luinil",
    "Malloriel", "Meneliel", "Mirimel", "Morniel", "Nimphelos", "Niphredil",
    "Rhiwen", "Silivren", "Tathariel", "Tinwen", "Uialwen", "Vanimelde",
    "Yulmiel",
]
const ELVISH_NAMES: NamesByGender = {
    male: ELVISH_MALE_NAMES,
    female: ELVISH_FEMALE_NAMES,
    neutral: [...ELVISH_MALE_NAMES, ...ELVISH_FEMALE_NAMES],
}

const MORDOR_MALE_NAMES = [
    "Agdush", "Akrum", "Azbuk", "Azog", "Bagronk", "Balgrum", "Bashnag",
    "Bolg", "Bolgath", "Borgul", "Bruzg", "Dakrul", "Dargoth", "Drubak",
    "Dugbur", "Durbag", "Durzak", "Dushnak", "Fangrak", "Gashnak", "Gazmug",
    "Ghazbur", "Golfimbul", "Gorbag", "Gorgath", "Gorlug", "Gothmog",
    "Grakk", "Grashbag", "Grimzak", "Grishnakh", "Grolbag", "Gromsh",
    "Gronk", "Grubdush", "Gruzzak", "Guldush", "Gulzog", "Haggak",
    "Hakdush", "Hurzag", "Kargath", "Karguk", "Krashnak", "Krugdush", "Kruk",
    "Lagduf", "Lagdush", "Lugbash", "Lugdush", "Lugrot", "Lurtz", "Magbuk",
    "Mauhur", "Mauzgul", "Mogdush", "Morbag", "Mozgul", "Mugrak", "Muzgash",
    "Muzgur", "Nargul", "Narzug", "Nazgob", "Ogbur", "Olgrak", "Orzag",
    "Pugrash", "Radbug", "Ragduf", "Ratbag", "Ruzgash", "Shagdush",
    "Shagrat", "Shakhbur", "Shazgul", "Shuzgul", "Skarn", "Skorg", "Snaga",
    "Snagrat", "Snarlug", "Thakrum", "Throk", "Thrugg", "Tugrak", "Ufthak",
    "Ugdush", "Ughlak", "Ugluk", "Ukbar", "Uldush", "Ulgash", "Urgash",
    "Uzbak", "Varguk", "Vorgash", "Vurbag", "Yagbur", "Yazhnak",
]
const MORDOR_FEMALE_NAMES = [
    "Agra", "Azash", "Azgra", "Bashka", "Bashra", "Bolgish", "Bolgra",
    "Borga", "Bruzka", "Dagra", "Dashka", "Draka", "Drubish", "Dugha",
    "Durgha", "Durza", "Dushra", "Fangra", "Garza", "Gasha", "Gashnish",
    "Gazma", "Ghashka", "Globa", "Gorlish", "Gorza", "Grasha", "Grimzish",
    "Grolka", "Gromsha", "Gruzka", "Guldish", "Gulka", "Hagga", "Hakra",
    "Hurza", "Hurzish", "Kagra", "Karga", "Karsha", "Krashnish", "Krugha",
    "Kruzha", "Lagdra", "Lagra", "Lugbish", "Lugha", "Lurka", "Magra",
    "Mauzga", "Mogdish", "Mogra", "Morza", "Mugra", "Muzga", "Nagra",
    "Narsha", "Narzish", "Nazga", "Oghra", "Olgrish", "Ogra", "Orzha",
    "Pugra", "Ragha", "Ratka", "Ruzga", "Ruzgish", "Shagdish", "Shagra",
    "Shakha", "Shazra", "Shuzga", "Skarna", "Skorga", "Snagra", "Snarlish",
    "Thakra", "Thraka", "Thrugga", "Tugra", "Tugrish", "Ugdish", "Ughla",
    "Ugra", "Ukra", "Ulgra", "Ulka", "Urgha", "Urgish", "Uzga", "Varga",
    "Vorsha", "Vurka", "Yagbish", "Yagra", "Yazha", "Zagra", "Zogra",
    "Zurga",
]
const MORDOR_NAMES: NamesByGender = {
    male: MORDOR_MALE_NAMES,
    female: MORDOR_FEMALE_NAMES,
    neutral: [...MORDOR_MALE_NAMES, ...MORDOR_FEMALE_NAMES],
}

export const MARKOV_NAME_PRESET_GROUPS: PresetGroup<string[]>[] = [
    buildStylePresetGroup("Japanese", JAPANESE_NAMES),
    buildStylePresetGroup("English", ENGLISH_NAMES),
    buildStylePresetGroup("Norse", NORSE_NAMES),
    buildStylePresetGroup("Latin", LATIN_NAMES),
    buildStylePresetGroup("Greek", GREEK_NAMES),
    buildStylePresetGroup("Fantasy", FANTASY_NAMES),
    buildStylePresetGroup("Elvish", ELVISH_NAMES),
    buildStylePresetGroup("Mordor", MORDOR_NAMES),
]
