import { Parameters } from "src/scripts/randomNameGenerator"

export const TESTING_PARAMETERS: Parameters = {
    minLength: 3,
    maxLength: 6,
    mustStartWith: "",
    mustEndWith: "",
    cannotStartWith: [],
    canEndWith: {},
    cannotEndWith: ["b", "qu"],
    lettersAfter: {
        a: {
            b: 1,
            qu: 1,
        },
        b: { a: 1, e: 1 },
        qu: { a: 1, e: 1 },
        e: {
            a: 1,
            b: 1,
            qu: 1,
        },
    },
}

export const DEFAULT_PARAMETERS: Parameters = {
    minLength: 4,
    maxLength: 6,
    mustStartWith: "",
    mustEndWith: "",
    cannotStartWith: [],
    canEndWith: {},
    cannotEndWith: ["qu", "x", "z", "g", "j", "v", "w"],
    lettersAfter: {
        a: {
            a: 1,
            b: 5,
            c: 4,
            d: 10,
            e: 2,
            f: 10,
            g: 10,
            h: 5,
            i: 2,
            j: 8,
            k: 4,
            l: 10,
            m: 10,
            n: 10,
            o: 2,
            p: 10,
            qu: 3,
            r: 10,
            s: 10,
            t: 10,
            u: 2,
            v: 5,
            w: 3,
            x: 3,
            y: 5,
            z: 5,
        },
        b: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        c: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        d: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        e: {
            a: 2,
            b: 5,
            c: 4,
            d: 10,
            e: 1,
            f: 10,
            g: 10,
            h: 5,
            i: 2,
            j: 8,
            k: 4,
            l: 10,
            m: 10,
            n: 10,
            o: 2,
            p: 10,
            qu: 3,
            r: 10,
            s: 10,
            t: 10,
            u: 2,
            v: 5,
            w: 3,
            x: 3,
            y: 5,
            z: 5,
        },
        f: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        g: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        h: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        i: {
            a: 2,
            b: 5,
            c: 4,
            d: 10,
            e: 2,
            f: 10,
            g: 10,
            h: 5,
            i: 1,
            j: 8,
            k: 4,
            l: 10,
            m: 10,
            n: 10,
            o: 3,
            p: 10,
            qu: 3,
            r: 10,
            s: 10,
            t: 10,
            u: 2,
            v: 5,
            w: 3,
            x: 3,
            y: 5,
            z: 5,
        },
        j: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        k: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        l: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        m: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        n: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        o: {
            a: 2,
            b: 5,
            c: 4,
            d: 10,
            e: 2,
            f: 10,
            g: 10,
            h: 5,
            i: 2,
            j: 8,
            k: 4,
            l: 10,
            m: 10,
            n: 10,
            o: 1,
            p: 10,
            qu: 3,
            r: 10,
            s: 10,
            t: 10,
            u: 2,
            v: 5,
            w: 3,
            x: 3,
            y: 5,
            z: 5,
        },
        p: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        qu: { a: 1, e: 1, i: 1, o: 1 },
        r: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        s: { a: 1, e: 1, i: 1, o: 1, u: 1, c: 1, t: 1, p: 1, k: 1, g: 1 },
        t: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        u: {
            a: 2,
            b: 5,
            c: 4,
            d: 10,
            e: 2,
            f: 10,
            g: 10,
            h: 5,
            i: 2,
            j: 8,
            k: 4,
            l: 10,
            m: 10,
            n: 10,
            o: 2,
            p: 10,
            qu: 3,
            r: 10,
            s: 10,
            t: 10,
            u: 1,
            v: 5,
            w: 3,
            x: 3,
            y: 5,
            z: 5,
        },
        v: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        w: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        x: { a: 1, e: 1, i: 1, o: 1, u: 1 },
        y: { a: 1, e: 1, o: 1, u: 1 },
        z: { a: 1, e: 1, i: 1, o: 1, u: 1 },
    },
}

export const JAPANESE_PARAMETERS: Parameters = {
    minLength: 3,
    maxLength: 5,
    mustStartWith: "",
    mustEndWith: "",
    cannotStartWith: [],
    canEndWith: {},
    cannotEndWith: [
        "b",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        "m",
        "p",
        "r",
        "s",
        "t",
        "w",
        "y",
        "z",
    ],
    lettersAfter: {
        a: {
            i: 1,
            u: 1,
            e: 1,
            o: 1,
            b: 3,
            d: 3,
            f: 3,
            g: 3,
            h: 3,
            j: 3,
            k: 3,
            m: 3,
            n: 3,
            p: 3,
            r: 3,
            s: 3,
            t: 3,
            w: 3,
            y: 3,
            z: 3,
        },
        b: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        d: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        e: {
            a: 1,
            i: 1,
            u: 1,
            o: 1,
            b: 3,
            d: 3,
            f: 3,
            g: 3,
            h: 3,
            j: 3,
            k: 3,
            m: 3,
            n: 3,
            p: 3,
            r: 3,
            s: 3,
            t: 3,
            w: 3,
            y: 3,
            z: 3,
        },
        f: { u: 1 },
        g: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        h: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        i: {
            a: 1,
            u: 1,
            e: 1,
            o: 1,
            b: 3,
            d: 3,
            f: 3,
            g: 3,
            h: 3,
            j: 3,
            k: 3,
            m: 3,
            n: 3,
            p: 3,
            r: 3,
            s: 3,
            t: 3,
            w: 3,
            y: 3,
            z: 3,
        },
        j: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        k: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        m: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        n: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        o: {
            a: 1,
            i: 1,
            u: 3,
            e: 1,
            b: 3,
            d: 3,
            f: 3,
            g: 3,
            h: 3,
            j: 3,
            k: 3,
            m: 3,
            n: 3,
            p: 3,
            r: 3,
            s: 3,
            t: 3,
            w: 3,
            y: 3,
            z: 3,
        },
        p: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        r: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        s: { a: 1, i: 1, u: 1, e: 1, o: 1 },
        t: { a: 1, u: 1, e: 1, o: 1 },
        u: {
            b: 3,
            d: 3,
            f: 3,
            g: 3,
            h: 3,
            j: 3,
            k: 3,
            m: 3,
            n: 3,
            p: 3,
            r: 3,
            s: 3,
            t: 3,
            w: 3,
            y: 3,
            z: 3,
        },
        w: { a: 1, u: 1, o: 1 },
        y: { a: 1, u: 1, o: 1 },
        z: { a: 1, i: 1, u: 1, e: 1, o: 1 },
    },
}
